function data_define(){
	poem_struct={
		poem_1:{
			sound: audio_recording_1,
			poem:"あきのたの　かりほのいほの　とまをあらみ　わがころもでは　つゆにぬれつつ",
			author:"天智天皇",
			part1:"あきのたのかりほのいほのとまをあらみ",
			part2:"わがころもではつゆにぬれつつ",
			line1:"わがころも",
			line2:"ではつゆに",
			line3:"ぬれつつ",
			mark_n: 5,
			mark_x: 1,
			mark_y: 3},
		poem_2:{
			sound: audio_recording_2,
			poem:"はるすぎて　なつきにけらし　しろたへの　ころもほすてふ　あまのかぐやま",
			author:"持統天皇",
			part1:"はるすぎてなつきにけらししろたへの",
			part2:"ころもほすてふあまのかぐやま",
			line1:"ころもほす",
			line2:"てふあまの",
			line3:"かぐやま",
			mark_n: 2,
			mark_x: 1,
			mark_y: 4},
		poem_3:{
			sound: audio_recording_3,
			poem:"あしびきの　やまどりのをの　しだりをの　ながながしよを　ひとりかもねむ",
			author:"柿本人麻呂",
			part1:"あしびきのやまどりのをのしだりをの",
			part2:"ながながしよをひとりかもねむ",
			line1:"ながながし",
			line2:"よをひとり",
			line3:"かもねむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_4:{
			sound: audio_recording_4,
			poem:"たごのうらに　うちいでてみれば　しろたへの　ふじのたかねに　ゆきはふりつつ",
			author:"山部赤人",
			part1:"たごのうらにうちいでてみればしろたへの",
			part2:"ふじのたかねにゆきはふりつつ",
			line1:"ふじのたか",
			line2:"ねにゆきは",
			line3:"ふりつつ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_5:{
			sound: audio_recording_5,
			poem:"おくやまに　もみぢふみわけ　なくしかの　こゑきくときぞ　あきはかなしき",
			author:"猿丸大夫",
			part1:"おくやまにもみぢふみわけなくしかの",
			part2:"こゑきくときぞあきはかなしき",
			line1:"こゑきくと",
			line2:"きぞあきは",
			line3:"かなしき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_6:{
			sound: audio_recording_6,
			poem:"かささぎの　わたせるはしに　おくしもの　しろきをみれば　よぞふけにける",
			author:"中納言家持",
			part1:"かささぎのわたせるはしにおくしもの",
			part2:"しろきをみればよぞふけにける",
			line1:"しろきをみ",
			line2:"ればよぞふ",
			line3:"けにける",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_7:{//あまの
			sound: audio_recording_7,
			poem:"あまのはら　ふりさけみれば　かすがなる　みかさのやまに　いでしつきかも",
			author:"安倍仲麿",
			part1:"あまのはらふりさけみればかすがなる",
			part2:"みかさのやまにいでしつきかも",
			line1:"みかさのや",
			line2:"まにいでし",
			line3:"つきかも",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_8:{
			sound: audio_recording_8,
			poem:"わがいほは　みやこのたつみ　しかぞすむ　よをうぢやまと　ひとはいふなり",
			author:"喜撰法師",
			part1:"わがいほはみやこのたつみしかぞすむ",
			part2:"よをうぢやまとひとはいふなり",
			line1:"よをうぢや",
			line2:"まとひとは",
			line3:"いふなり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_9:{
			sound: audio_recording_9,
			poem:"はなのいろは　うつりにけりな　いたづらに　わがみよにふる　ながめせしまに",
			author:"小野小町",
			part1:"はなのいろはうつりにけりないたづらに",
			part2:"わがみよにふるながめせしまに",
			line1:"わがみよに",
			line2:"ふるながめ",
			line3:"せしまに",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_10:{
			sound: audio_recording_10,
			poem:"これやこの　ゆくもかへるも　わかれては　しるもしらぬも　あふさかのせき",
			author:"蝉丸",
			part1:"これやこのゆくもかへるもわかれては",
			part2:"しるもしらぬもあふさかのせき",
			line1:"しるもしら",
			line2:"ぬもあふさ",
			line3:"かのせき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_11:{
			sound: audio_recording_11,
			poem:"わたのはら　やそしまかけて　こぎいでぬと　ひとにはつげよ　あまのつりぶね",
			author:"参議篁",
			part1:"わたのはらやそしまかけてこぎいでぬと",
			part2:"ひとにはつげよあまのつりぶね",
			line1:"ひとにはつ",
			line2:"げよあまの",
			line3:"つりぶね",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_12:{//あまつ
			sound: audio_recording_12,
			poem:"あまつかぜ　くものかよひぢ　ふきとぢよ　をとめのすがた　しばしとどめむ",
			author:"僧正遍照",
			part1:"あまつかぜくものかよひぢふきとぢよ",
			part2:"をとめのすがたしばしとどめむ",
			line1:"をとめのす",
			line2:"がたしばし",
			line3:"とどめむ",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_13:{
			sound: audio_recording_13,
			poem:"つくばねの　みねよりおつる　みなのがは　こひぞつもりて　ふちとなりぬる",
			author:"陽成院",
			part1:"つくばねのみねよりおつるみなのがは",
			part2:"こひぞつもりてふちとなりぬる",
			line1:"こひぞつも",
			line2:"りてふちと",
			line3:"なりぬる",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_14:{
			sound: audio_recording_14,
			poem:"みちのくの　しのぶもぢずり　たれゆゑに　みだれそめにし　われならなくに",
			author:"河原左大臣",
			part1:"みちのくのしのぶもぢずりたれゆゑに",
			part2:"みだれそめにしわれならなくに",
			line1:"みだれそめ",
			line2:"にしわれな",
			line3:"らなくに",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_15:{
			sound: audio_recording_15,
			poem:"きみがため　はるののにいでて　わかなつむ　わがころもでに　ゆきはふりつつ",
			author:"光孝天皇",
			part1:"きみがためはるののにいでてわかなつむ",
			part2:"わがころもでにゆきはふりつつ",
			line1:"わがころも",
			line2:"でにゆきは",
			line3:"ふりつつ",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_16:{
			sound: audio_recording_16,
			poem:"たちわかれ　いなばのやまの　みねにおふる　まつとしきかば　いまかへりこむ",
			author:"中納言行平",
			part1:"たちわかれいなばのやまのみねにおふる",
			part2:"まつとしきかばいまかへりこむ",
			line1:"まつとしき",
			line2:"かばいまか",
			line3:"へりこむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_17:{
			sound: audio_recording_17,
			poem:"ちはやぶる　かみよもきかず　たつたがは　からくれなゐに　みづくくるとは",
			author:"在原業平朝臣",
			part1:"ちはやぶるかみよもきかずたつたがは",
			part2:"からくれなゐにみづくくるとは",
			line1:"からくれな",
			line2:"ゐにみづく",
			line3:"くるとは",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_18:{
			sound: audio_recording_18,
			poem:"すみのえの　きしによるなみ　よるさへや　ゆめのかよひぢ　ひとめよくらむ",
			author:"藤原敏行朝臣",
			part1:"すみのえのきしによるなみよるさへや",
			part2:"ゆめのかよひぢひとめよくらむ",
			line1:"ゆめのかよ",
			line2:"ひぢひとめ",
			line3:"よくらむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_19:{
			sound: audio_recording_19,
			poem:"なにはがた　みじかきあしの　ふしのまも　あはでこのよを　すぐしてよとや",
			author:"伊勢",
			part1:"なにはがたみじかきあしのふしのまも",
			part2:"あはでこのよをすぐしてよとや",
			line1:"あはでこの",
			line2:"よをすぐし",
			line3:"てよとや",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_20:{
			sound: audio_recording_20,
			poem:"わびぬれば　いまはたおなじ　なにはなる　みをつくしても　あはむとぞおもふ",
			author:"元良親王",
			part1:"わびぬればいまはたおなじなにはなる",
			part2:"みをつくしてもあはむとぞおもふ",
			line1:"みをつくし",
			line2:"てもあはむ",
			line3:"とぞおもふ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_21:{
			sound: audio_recording_21,
			poem:"いまこむと　いひしばかりに　ながつきの　ありあけのつきを　まちいでつるかな",
			author:"素性法師",
			part1:"いまこむといひしばかりにながつきの",
			part2:"ありあけのつきをまちいでつるかな",
			line1:"ありあけの",
			line2:"つきをまち",
			line3:"いでつるかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_22:{
			sound: audio_recording_22,
			poem:"ふくからに　あきのくさきの　しをるれば　むべやまかぜを　あらしといふらむ",
			author:"文屋康秀",
			part1:"ふくからにあきのくさきのしをるれば",
			part2:"むべやまかぜをあらしといふらむ",
			line1:"むべやまか",
			line2:"ぜをあらし",
			line3:"といふらむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_23:{
			sound: audio_recording_23,
			poem:"つきみれば　ちぢにものこそ　かなしけれ　わがみひとつの　あきにはあらねど",
			author:"大江千里",
			part1:"つきみればちぢにものこそかなしけれ",
			part2:"わがみひとつのあきにはあらねど",
			line1:"わがみひと",
			line2:"つのあきに",
			line3:"はあらねど",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_24:{
			sound: audio_recording_24,
			poem:"このたびは　ぬさもとりあへず　たむけやま　もみぢのにしき　かみのまにまに",
			author:"菅家",
			part1:"このたびはぬさもとりあへずたむけやま",
			part2:"もみぢのにしきかみのまにまに",
			line1:"もみぢのに",
			line2:"しきかみの",
			line3:"まにまに",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_25:{
			sound: audio_recording_25,
			poem:"なにしおはば　あふさかやまの　さねかづら　ひとにしられで　くるよしもがな",
			author:"三条右大臣",
			part1:"なにしおはばあふさかやまのさねかづら",
			part2:"ひとにしられでくるよしもがな",
			line1:"ひとにしら",
			line2:"れでくるよ",
			line3:"しもがな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_26:{
			sound: audio_recording_26,
			poem:"をぐらやま　みねのもみぢば　こころあらば　いまひとたびの　みゆきまたなむ",
			author:"貞信公",
			part1:"をぐらやまみねのもみぢばこころあらば",
			part2:"いまひとたびのみゆきまたなむ",
			line1:"いまひとた",
			line2:"びのみゆき",
			line3:"またなむ",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_27:{
			sound: audio_recording_27,
			poem:"みかのはら　わきてながるる　いづみがは　いつみきとてか　こひしかるらむ",
			author:"中納言兼輔",
			part1:"みかのはらわきてながるるいづみがは",
			part2:"いつみきとてかこひしかるらむ",
			line1:"いつみきと",
			line2:"てかこひし",
			line3:"かるらむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_28:{
			sound: audio_recording_28,
			poem:"やまざとは　ふゆぞさびしさ　まさりける　ひとめもくさも　かれぬとおもへば",
			author:"源宗于朝臣",
			part1:"やまざとはふゆぞさびしさまさりける",
			part2:"ひとめもくさもかれぬとおもへば",
			line1:"ひとめもく",
			line2:"さもかれぬ",
			line3:"とおもへば",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_29:{
			sound: audio_recording_29,
			poem:"こころあてに　をらばやをらむ　はつしもの　おきまどはせる　しらぎくのはな",
			author:"凡河内躬恒",
			part1:"こころあてにをらばやをらむはつしもの",
			part2:"おきまどはせるしらぎくのはな",
			line1:"おきまどは",
			line2:"せるしらぎ",
			line3:"くのはな",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_30:{//ありあ
			sound: audio_recording_30,
			poem:"ありあけの　つれなくみえし　わかれより　あかつきばかり　うきものはなし",
			author:"壬生忠岑",
			part1:"ありあけのつれなくみえしわかれより",
			part2:"あかつきばかりうきものはなし",
			line1:"あかつきば",
			line2:"かりうきも",
			line3:"のはなし",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_31:{
			sound: audio_recording_31,
			poem:"あさぼらけ　ありあけのつきと　みるまでに　よしののさとに　ふれるしらゆき",
			author:"坂上是則",
			part1:"あさぼらけありあけのつきとみるまでに",
			part2:"よしののさとにふれるしらゆき",
			line1:"よしののさ",
			line2:"とにふれる",
			line3:"しらゆき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_32:{
			sound: audio_recording_32,
			poem:"やまがはに　かぜのかけたる　しがらみは　ながれもあへぬ　もみぢなりけり",
			author:"春道列樹",
			part1:"やまがはにかぜのかけたるしがらみは",
			part2:"ながれもあへぬもみぢなりけり",
			line1:"ながれもあ",
			line2:"へぬもみぢ",
			line3:"なりけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_33:{
			sound: audio_recording_33,
			poem:"ひさかたの　ひかりのどけき　はるのひに　しづごころなく　はなのちるらむ",
			author:"紀友則",
			part1:"ひさかたのひかりのどけきはるのひに",
			part2:"しづごころなくはなのちるらむ",
			line1:"しづごころ",
			line2:"なくはなの",
			line3:"ちるらむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_34:{
			sound: audio_recording_34,
			poem:"たれをかも　しるひとにせむ　たかさごの　まつもむかしの　ともならなくに",
			author:"藤原興風",
			part1:"たれをかもしるひとにせむたかさごの",
			part2:"まつもむかしのともならなくに",
			line1:"まつもむか",
			line2:"しのともな",
			line3:"らなくに",
			mark_s:"たれ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_35:{
			sound: audio_recording_35,
			poem:"ひとはいさ　こころもしらず　ふるさとは　はなぞむかしの　かににほひける",
			author:"紀貫之",
			part1:"ひとはいさこころもしらずふるさとは",
			part2:"はなぞむかしのかににほひける",
			line1:"はなぞむか",
			line2:"しのかにに",
			line3:"ほひける",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_36:{
			sound: audio_recording_36,
			poem:"なつのよは　まだよひながら　あけぬるを　くものいづこに　つきやどるらむ",
			author:"清原深養父",
			part1:"なつのよはまだよひながらあけぬるを",
			part2:"くものいづこにつきやどるらむ",
			line1:"くものいづ",
			line2:"こにつきや",
			line3:"どるらむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_37:{
			sound: audio_recording_37,
			poem:"しらつゆに　かぜのふきしく　あきののは　つらぬきとめぬ　たまぞちりける",
			author:"文屋朝康",
			part1:"しらつゆにかぜのふきしくあきののは",
			part2:"つらぬきとめぬたまぞちりける",
			line1:"つらぬきと",
			line2:"めぬたまぞ",
			line3:"ちりける",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_38:{
			sound: audio_recording_38,
			poem:"わすらるる　みをばおもはず　ちかひてし　ひとのいのちの　をしくもあるかな",
			author:"右近",
			part1:"わすらるるみをばおもはずちかひてし",
			part2:"ひとのいのちのをしくもあるかな",
			line1:"ひとのいの",
			line2:"ちのをしく",
			line3:"もあるかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_39:{//あさじ
			sound: audio_recording_39,
			poem:"あさぢふの　をののしのはら　しのぶれど　あまりてなどか　ひとのこひしき",
			author:"参議等",
			part1:"あさぢふのをののしのはらしのぶれど",
			part2:"あまりてなどかひとのこひしき",
			line1:"あまりてな",
			line2:"どかひとの",
			line3:"こひしき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_40:{
			sound: audio_recording_40,
			poem:"しのぶれど　いろにいでにけり　わがこひは　ものやおもふと　ひとのとふまで",
			author:"平兼盛",
			part1:"しのぶれどいろにいでにけりわがこひは",
			part2:"ものやおもふとひとのとふまで",
			line1:"ものやおも",
			line2:"ふとひとの",
			line3:"とふまで",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_41:{
			sound: audio_recording_41,
			poem:"こひすてふ　わがなはまだき　たちにけり　ひとしれずこそ　おもひそめしか",
			author:"壬生忠見",
			part1:"こひすてふわがなはまだきたちにけり",
			part2:"ひとしれずこそおもひそめしか",
			line1:"ひとしれず",
			line2:"こそおもひ",
			line3:"そめしか",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_42:{
			sound: audio_recording_42,
			poem:"ちぎりきな　かたみにそでを　しぼりつつ　すゑのまつやま　なみこさじとは",
			author:"清原元輔",
			part1:"ちぎりきなかたみにそでをしぼりつつ",
			part2:"すゑのまつやまなみこさじとは",
			line1:"すゑのまつ",
			line2:"やまなみこ",
			line3:"さじとは",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_43:{//あい
			sound: audio_recording_43,
			poem:"あひみての　のちのこころに　くらぶれば　むかしはものを　おもはざりけり",
			author:"権中納言敦忠",
			part1:"あひみてののちのこころにくらぶれば",
			part2:"むかしはものをおもはざりけり",
			line1:"むかしはも",
			line2:"のをおもは",
			line3:"ざりけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_44:{
			sound: audio_recording_44,
			poem:"あふことの　たえてしなくは　なかなかに　ひとをもみをも　うらみざらまし",
			author:"中納言朝忠",
			part1:"あふことのたえてしなくはなかなかに",
			part2:"ひとをもみをもうらみざらまし",
			line1:"ひとをもみ",
			line2:"をもうらみ",
			line3:"ざらまし",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_45:{//あわれ
			sound: audio_recording_45,
			poem:"あはれとも　いふべき人は　思ほえで　身のいたづらに　なりぬべきかな",
			author:"謙徳公",
			part1:"あはれともいふべき人は思ほえで",
			part2:"身のいたづらになりぬべきかな",
			line1:"身のいたづ",
			line2:"らになりぬ",
			line3:"べきかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_46:{
			sound: audio_recording_46,
			poem:"ゆらのとを　わたるふなびと　かぢをたえ　ゆくへもしらぬ　こひのみちかな",
			author:"曾禰好忠",
			part1:"ゆらのとをわたるふなびとかぢをたえ",
			part2:"ゆくへもしらぬこひのみちかな",
			line1:"ゆくへもし",
			line2:"らぬこひの",
			line3:"みちかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_47:{
			sound: audio_recording_47,
			poem:"やへむぐら　しげれるやどの　さびしきに　ひとこそみえね　あきはきにけり",
			author:"恵慶法師",
			part1:"やへむぐらしげれるやどのさびしきに",
			part2:"ひとこそみえねあきはきにけり",
			line1:"ひとこそみ",
			line2:"えねあきは",
			line3:"きにけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_48:{
			sound: audio_recording_48,
			poem:"かぜをいたみ　いはうつなみの　おのれのみ　くだけてものを　おもふころかな",
			author:"源重之",
			part1:"かぜをいたみいはうつなみのおのれのみ",
			part2:"くだけてものをおもふころかな",
			line1:"くだけても",
			line2:"のをおもふ",
			line3:"ころかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_49:{
			sound: audio_recording_49,
			poem:"みかきもり　ゑじのたくひの　よるはもえ　ひるはきえつつ　ものをこそおもへ",
			author:"大中臣能宣",
			part1:"みかきもりゑじのたくひのよるはもえ",
			part2:"ひるはきえつつものをこそおもへ",
			line1:"ひるはきえ",
			line2:"つつものを",
			line3:"こそおもへ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_50:{
			sound: audio_recording_50,
			poem:"きみがため　をしからざりし　いのちさへ　ながくもがなと　おもひけるかな",
			author:"藤原義孝",
			part1:"きみがためをしからざりしいのちさへ",
			part2:"ながくもがなとおもひけるかな",
			line1:"ながくもが",
			line2:"なとおもひ",
			line3:"けるかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_51:{
			sound: audio_recording_51,
			poem:"かくとだに　えやはいぶきの　さしもぐさ　さしもしらじな　もゆるおもひを",
			author:"藤原実方朝臣",
			part1:"かくとだにえやはいぶきのさしもぐさ",
			part2:"さしもしらじなもゆるおもひを",
			line1:"さしもしら",
			line2:"じなもゆる",
			line3:"おもひを",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_52:{
			sound: audio_recording_52,
			poem:"あけぬれば　くるるものとは　しりながら　なほうらめしき　あさぼらけかな",
			author:"藤原道信朝臣",
			part1:"あけぬればくるるものとはしりながら",
			part2:"なほうらめしきあさぼらけかな",
			line1:"なほうらめ",
			line2:"しきあさぼ",
			line3:"らけかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_53:{
			sound: audio_recording_53,
			poem:"なげきつつ　ひとりぬるよの　あくるまは　いかにひさしき　ものとかはしる",
			author:"右大将道綱母",
			part1:"なげきつつひとりぬるよのあくるまは",
			part2:"いかにひさしきものとかはしる",
			line1:"いかにひさ",
			line2:"しきものと",
			line3:"かはしる",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_54:{
			sound: audio_recording_54,
			poem:"わすれじの　ゆくすゑまでは　かたければ　けふをかぎりの　いのちともがな",
			author:"儀同三司母",
			part1:"わすれじのゆくすゑまではかたければ",
			part2:"けふをかぎりのいのちともがな",
			line1:"けふをかぎ",
			line2:"りのいのち",
			line3:"ともがな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_55:{
			sound: audio_recording_55,//たき
			poem:"たきのおとは　たえてひさしく　なりぬれど　なこそながれて　なほきこえけれ",
			author:"大納言公任",
			part1:"たきのおとはたえてひさしくなりぬれど",
			part2:"なこそながれてなほきこえけれ",
			line1:"なこそなが",
			line2:"れてなほき",
			line3:"こえけれ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_56:{//あらざ
			sound: audio_recording_56,
			poem:"あらざらむ　このよのほかの　おもひでに　いまひとたびの　あふこともがな",
			author:"和泉式部",
			part1:"あらざらむこのよのほかのおもひでに",
			part2:"いまひとたびのあふこともがな",
			line1:"いまひとた",
			line2:"びのあふこ",
			line3:"ともがな",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_57:{
			sound: audio_recording_57,
			poem:"めぐりあひて　みしやそれとも　わかぬまに　くもがくれにし　よはのつきかな",
			author:"紫式部",
			part1:"めぐりあひてみしやそれともわかぬまに",
			part2:"くもがくれにしよはのつきかな",
			line1:"くもがくれ",
			line2:"にしよはの",
			line3:"つきかな",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_58:{//ありま
			sound: audio_recording_58,
			poem:"ありまやま　ゐなのささはら　かぜふけば　いでそよひとを　わすれやはする",
			author:"大弐三位",
			part1:"ありまやまゐなのささはらかぜふけば",
			part2:"いでそよひとをわすれやはする",
			line1:"いでそよひ",
			line2:"とをわすれ",
			line3:"やはする",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_59:{
			sound: audio_recording_59,
			poem:"やすらはで　ねなましものを　さよふけて　かたぶくまでの　つきをみしかな",
			author:"赤染衛門",
			part1:"やすらはでねなましものをさよふけて",
			part2:"かたぶくまでのつきをみしかな",
			line1:"かたぶくま",
			line2:"でのつきを",
			line3:"みしかな",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_60:{//おおえ
			sound: audio_recording_60,
			poem:"おほえやま　いくののみちの　とほければ　まだふみもみず　あまのはしだて",
			author:"小式部内侍",
			part1:"おほえやまいくののみちのとほければ",
			part2:"まだふみもみずあまのはしだて",
			line1:"まだふみも",
			line2:"みずあまの",
			line3:"はしだて",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_61:{
			sound: audio_recording_61,
			poem:"いにしへの　ならのみやこの　やへざくら　けふここのへに　にほひぬるかな",
			author:"伊勢大輔",
			part1:"いにしへのならのみやこのやへざくら",
			part2:"けふここのへににほひぬるかな",
			line1:"けふここの",
			line2:"へににほひ",
			line3:"ぬるかな",
			mark_n: 4,
			mark_x: 2,
			mark_y: 2},
		poem_62:{
			sound: audio_recording_62,
			poem:"よをこめて　とりのそらねは　はかるとも　よにあふさかの　せきはゆるさじ",
			author:"清少納言",
			part1:"よをこめてとりのそらねははかるとも",
			part2:"よにあふさかのせきはゆるさじ",
			line1:"よにあふさ",
			line2:"かのせきは",
			line3:"ゆるさじ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_63:{
			sound: audio_recording_63,
			poem:"いまはただ　おもひたえなむ　とばかりを　ひとづてならで　いふよしもがな",
			author:"左京大夫道雅",
			part1:"いまはただおもひたえなむとばかりを",
			part2:"ひとづてならでいふよしもがな",
			line1:"ひとづてな",
			line2:"らでいふよ",
			line3:"しもがな",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_64:{//あさぼらけう
			sound: audio_recording_64,
			poem:"あさぼらけ　うぢのかはぎり　たえだえに　あらはれわたる　せぜのあじろぎ",
			author:"権中納言定頼",
			part1:"あさぼらけうぢのかはぎりたえだえに",
			part2:"あらはれわたるせぜのあじろぎ",
			line1:"あらはれわ",
			line2:"たるせぜの",
			line3:"あじろぎ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_65:{
			sound: audio_recording_65,
			poem:"うらみわび　ほさぬそでだに　あるものを　こひにくちなむ　なこそをしけれ",
			author:"相模",
			part1:"うらみわびほさぬそでだにあるものを",
			part2:"こひにくちなむなこそをしけれ",
			line1:"こひにくち",
			line2:"なむなこそ",
			line3:"をしけれ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_66:{
			sound: audio_recording_66,
			poem:"もろともに　あはれとおもへ　やまざくら　はなよりほかに　しるひともなし",
			author:"前大僧正行尊",
			part1:"もろともにあはれとおもへやまざくら",
			part2:"はなよりほかにしるひともなし",
			line1:"はなよりほ",
			line2:"かにしるひ",
			line3:"ともなし",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_67:{
			sound: audio_recording_67,
			poem:"はるのよの　ゆめばかりなる　たまくらに　かひなくたたむ　なこそをしけれ",
			author:"周防内侍",
			part1:"はるのよのゆめばかりなるたまくらに",
			part2:"かひなくたたむなこそをしけれ",
			line1:"かひなくた",
			line2:"たむなこそ",
			line3:"をしけれ",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_68:{
			sound: audio_recording_68,
			poem:"こころにも　あらでうきよに　ながらへば　こひしかるべき　よはのつきかな",
			author:"三条院",
			part1:"こころにもあらでうきよにながらへば",
			part2:"こひしかるべきよはのつきかな",
			line1:"こひしかる",
			line2:"べきよはの",
			line3:"つきかな",
			mark_s:"こころに",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_69:{//あらし
			sound: audio_recording_69,
			poem:"あらしふく　みむろのやまの　もみぢばは　たつたのかはの　にしきなりけり",
			author:"能因法師",
			part1:"あらしふくみむろのやまのもみぢばは",
			part2:"たつたのかはのにしきなりけり",
			line1:"たつたのか",
			line2:"はのにしき",
			line3:"なりけり",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_70:{
			sound: audio_recording_70,
			poem:"さびしさに　やどをたちいでて　ながむれば　いづこもおなじ　あきのゆふぐれ",
			author:"良暹法師",
			part1:"さびしさにやどをたちいでてながむれば",
			part2:"いづこもおなじあきのゆふぐれ",
			line1:"いづこもお",
			line2:"なじあきの",
			line3:"ゆふぐれ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_71:{//あし
			sound: audio_recording_71,
			poem:"ゆふされば　かどたのいなば　おとづれて　あしのまろやに　あきかぜぞふく",
			author:"大納言経信",
			part1:"ゆふさればかどたのいなばおとづれて",
			part2:"あしのまろやにあきかぜぞふく",
			line1:"あしのまろ",
			line2:"やにあきか",
			line3:"ぜぞふく",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_72:{
			sound: audio_recording_72,
			poem:"おとにきく　たかしのはまの　あだなみは　かけじやそでの　ぬれもこそすれ",
			author:"祐子内親王家紀伊",
			part1:"おとにきくたかしのはまのあだなみは",
			part2:"かけじやそでのぬれもこそすれ",
			line1:"かけじやそ",
			line2:"でのぬれも",
			line3:"こそすれ",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_73:{
			sound: audio_recording_73,
			poem:"たかさごの　をのへのさくら　さきにけり　とやまのかすみ　たたずもあらなむ",
			author:"権中納言匡房",
			part1:"たかさごのをのへのさくらさきにけり",
			part2:"とやまのかすみたたずもあらなむ",
			line1:"とやまのか",
			line2:"すみたたず",
			line3:"もあらなむ",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_74:{
			sound: audio_recording_74,
			poem:"うかりける　ひとをはつせの　やまおろしよ　はげしかれとは　いのらぬものを",
			author:"源俊頼朝臣",
			part1:"うかりけるひとをはつせのやまおろしよ",
			part2:"はげしかれとはいのらぬものを",
			line1:"はげしかれ",
			line2:"とはいのら",
			line3:"ぬものを",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_75:{
			sound: audio_recording_75,
			poem:"ちぎりおきし　させもがつゆを　いのちにて　あはれことしの　あきもいぬめり",
			author:"藤原基俊",
			part1:"ちぎりおきしさせもがつゆをいのちにて",
			part2:"あはれことしのあきもいぬめり",
			line1:"あはれこと",
			line2:"しのあきも",
			line3:"いぬめり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_76:{
			sound: audio_recording_76,
			poem:"わたのはら　こぎいでてみれば　ひさかたの　くもゐにまがふ　おきつしらなみ",
			author:"法性寺入道前関白太政大臣",
			part1:"わたのはらこぎいでてみればひさかたの",
			part2:"くもゐにまがふおきつしらなみ",
			line1:"くもゐにま",
			line2:"がふおきつ",
			line3:"しらなみ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_77:{
			sound: audio_recording_77,
			poem:"せをはやみ　いはにせかるる　たきがはの　われてもすゑに　あはむとぞおもふ",
			author:"崇徳院",
			part1:"せをはやみいはにせかるるたきがはの",
			part2:"われてもすゑにあはむとぞおもふ",
			line1:"われてもす",
			line2:"ゑにあはむ",
			line3:"とぞおもふ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_78:{//あわじ
			sound: audio_recording_78,
			poem:"あはぢしま　かよふちどりの　なくこゑに　いくよねざめぬ　すまのせきもり",
			author:"源兼昌",
			part1:"あはぢしまかよふちどりのなくこゑに",
			part2:"いくよねざめぬすまのせきもり",
			line1:"いくよねざ",
			line2:"めぬすまの",
			line3:"せきもり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_79:{//あきか
			sound: audio_recording_79,
			poem:"あきかぜに　たなびくくもの　たえまより　もれいづるつきの　かげのさやけさ",
			author:"左京大夫顕輔",
			part1:"あきかぜにたなびくくものたえまより",
			part2:"もれいづるつきのかげのさやけさ",
			line1:"もれいづる",
			line2:"つきのかげ",
			line3:"のさやけさ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_80:{
			sound: audio_recording_80,
			poem:"ながからむ　こころもしらず　くろかみの　みだれてけさは　ものをこそおもへ",
			author:"待賢門院堀河",
			part1:"ながからむこころもしらずくろかみの",
			part2:"みだれてけさはものをこそおもへ",
			line1:"みだれてけ",
			line2:"さはものを",
			line3:"こそおもへ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_81:{
			sound: audio_recording_81,
			poem:"ほととぎす　なきつるかたを　ながむれば　ただありあけの　つきぞのこれる",
			author:"後徳大寺左大臣",
			part1:"ほととぎすなきつるかたをながむれば",
			part2:"ただありあけのつきぞのこれる",
			line1:"ただありあ",
			line2:"けのつきぞ",
			line3:"のこれる",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_82:{
			sound: audio_recording_82,
			poem:"おもひわび　さてもいのちは　あるものを　うきにたへぬは　なみだなりけり",
			author:"道因法師",
			part1:"おもひわびさてもいのちはあるものを",
			part2:"うきにたへぬはなみだなりけり",
			line1:"うきにたへ",
			line2:"ぬはなみだ",
			line3:"なりけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_83:{
			sound: audio_recording_83,
			poem:"よのなかよ　みちこそなけれ　おもひいる　やまのおくにも　しかぞなくなる",
			author:"皇太后宮大夫俊成",
			part1:"よのなかよみちこそなけれおもひいる",
			part2:"やまのおくにもしかぞなくなる",
			line1:"やまのおく",
			line2:"にもしかぞ",
			line3:"なくなる",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_84:{//ながら
			sound: audio_recording_84,
			poem:"ながらへば　またこのごろや　しのばれむ　うしとみしよぞ　いまはこひしき",
			author:"藤原清輔朝臣",
			part1:"ながらへばまたこのごろやしのばれむ",
			part2:"うしとみしよぞいまはこひしき",
			line1:"うしとみし",
			line2:"よぞいまは",
			line3:"こひしき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_85:{
			sound: audio_recording_85,
			poem:"よもすがら　ものおもふころは　あけやらで　ねやのひまさへ　つれなかりけり",
			author:"俊恵法師",
			part1:"よもすがらものおもふころはあけやらで",
			part2:"ねやのひまさへつれなかりけり",
			line1:"ねやのひま",
			line2:"さへつれな",
			line3:"かりけり",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_86:{
			sound: audio_recording_86,
			poem:"なげけとて　つきやはものを　おもはする　かこちがほなる　わがなみだかな",
			author:"西行法師",
			part1:"なげけとてつきやはものをおもはする",
			part2:"かこちがほなるわがなみだかな",
			line1:"かこちがほ",
			line2:"なるわがな",
			line3:"みだかな",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_87:{
			sound: audio_recording_87,
			poem:"むらさめの　つゆもまだひぬ　まきのはに　きりたちのぼる　あきのゆふぐれ",
			author:"寂蓮法師",
			part1:"むらさめのつゆもまだひぬまきのはに",
			part2:"きりたちのぼるあきのゆふぐれ",
			line1:"きりたちの",
			line2:"ぼるあきの",
			line3:"ゆふぐれ",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_88:{//なにわえ
			sound: audio_recording_88,
			poem:"なにはえの　あしのかりねの　ひとよゆゑ　みをつくしてや　こひわたるべき",
			author:"皇嘉門院別当",
			part1:"なにはえのあしのかりねのひとよゆゑ",
			part2:"みをつくしてやこひわたるべき",
			line1:"みをつくし",
			line2:"てやこひわ",
			line3:"たるべき",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_89:{
			sound: audio_recording_89,
			poem:"たまのをよ　たえなばたえね　ながらへば　しのぶることの　よわりもぞする",
			author:"式子内親王",
			part1:"たまのをよたえなばたえねながらへば",
			part2:"しのぶることのよわりもぞする",
			line1:"しのぶるこ",
			line2:"とのよわり",
			line3:"もぞする",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_90:{
			sound: audio_recording_90,
			poem:"みせばやな　をじまのあまの　そでだにも　ぬれにぞぬれし　いろはかはらず",
			author:"殷富門院大輔",
			part1:"みせばやなをじまのあまのそでだにも",
			part2:"ぬれにぞぬれしいろはかはらず",
			line1:"ぬれにぞぬ",
			line2:"れしいろは",
			line3:"かはらず",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_91:{
			sound: audio_recording_91,
			poem:"きりぎりす　なくやしもよの　さむしろに　ころもかたしき　ひとりかもねむ",
			author:"後京極摂政前太政大臣",
			part1:"きりぎりすなくやしもよのさむしろに",
			part2:"ころもかたしきひとりかもねむ",
			line1:"ころもかた",
			line2:"しきひとり",
			line3:"かもねむ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_92:{
			sound: audio_recording_92,
			poem:"わがそでは　しほひにみえぬ　おきのいしの　ひとこそしらね　かわくまもなし",
			author:"二条院讃岐",
			part1:"わがそではしほひにみえぬおきのいしの",
			part2:"ひとこそしらねかわくまもなし",
			line1:"ひとこそし",
			line2:"らねかわく",
			line3:"まもなし",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_93:{
			sound: audio_recording_93,
			poem:"よのなかは　つねにもがもな　なぎさこぐ　あまのをぶねの　つなでかなしも",
			author:"鎌倉右大臣",
			part1:"よのなかはつねにもがもななぎさこぐ",
			part2:"あまのをぶねのつなでかなしも",
			line1:"あまのをぶ",
			line2:"ねのつなで",
			line3:"かなしも",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_94:{
			sound: audio_recording_94,
			poem:"みよしのの　やまのあきかぜ　さよふけて　ふるさとさむく　ころもうつなり",
			author:"参議雅経",
			part1:"みよしののやまのあきかぜさよふけて",
			part2:"ふるさとさむくころもうつなり",
			line1:"ふるさとさ",
			line2:"むくころも",
			line3:"うつなり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_95:{
			sound: audio_recording_95,
			poem:"おほけなく　うきよのたみに　おほふかな　わがたつそまに　すみぞめのそで",
			author:"前大僧正慈円",
			part1:"おほけなくうきよのたみにおほふかな",
			part2:"わがたつそまにすみぞめのそで",
			line1:"わがたつそ",
			line2:"まにすみぞ",
			line3:"めのそで",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_96:{
			sound: audio_recording_96,
			poem:"はなさそふ　あらしのにはの　ゆきならで　ふりゆくものは　わがみなりけり",
			author:"入道前太政大臣",
			part1:"はなさそふあらしのにはのゆきならで",
			part2:"ふりゆくものはわがみなりけり",
			line1:"ふりゆくも",
			line2:"のはわがみ",
			line3:"なりけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_97:{
			sound: audio_recording_97,
			poem:"こぬひとを　まつほのうらの　ゆふなぎに　やくやもしほの　みもこがれつつ",
			author:"権中納言定家",
			part1:"こぬひとをまつほのうらのゆふなぎに",
			part2:"やくやもしほのみもこがれつつ",
			line1:"やくやもし",
			line2:"ほのみもこ",
			line3:"がれつつ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_98:{
			sound: audio_recording_98,
			poem:"かぜそよぐ　ならのをがはの　ゆふぐれは　みそぎぞなつの　しるしなりける",
			author:"従二位家隆",
			part1:"かぜそよぐならのをがはのゆふぐれは",
			part2:"みそぎぞなつのしるしなりける",
			line1:"みそぎぞな",
			line2:"つのしるし",
			line3:"なりける",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_99:{
			sound: audio_recording_99,
			poem:"ひともをし　ひともうらめし　あぢきなく　よをおもふゆゑに　ものおもふみは",
			author:"後鳥羽院",
			part1:"ひともをしひともうらめしあぢきなく",
			part2:"よをおもふゆゑにものおもふみは",
			line1:"よをおもふ",
			line2:"ゆゑにもの",
			line3:"おもふみは",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_100:{
			sound: audio_recording_100,
			poem:"ももしきや　ふるきのきばの　しのぶにも　なほあまりある　むかしなりけり",
			author:"順徳院",
			part1:"ももしきやふるきのきばのしのぶにも",
			part2:"なほあまりあるむかしなりけり",
			line1:"なほあまり",
			line2:"あるむかし",
			line3:"なりけり",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},

	}
}