//fix audio 20			
function data_define(){			
	poem_struct={		
		poem_1:{	
			sound1: recording_001_a, sound2: recording_001_b,
			poem:"あきのたの　かりほのいほの　とまをあらみ　わがころもでは　つゆにぬれつつ",
			name_e:"天智天皇",
			part1:"あきのたのかりほのいほのとまをあらみ",
			part2:"わがころもではつゆにぬれつつ",
			line1:"わがころも",
			line2:"ではつゆに",
			line3:"ぬれつつ",
			name_j: "Tenchi Tenno",
			second_verse_answer: "わかころもては",
			kimariji: "あきの",
			translation: "Coarse the rush-mat roof|Sheltering the harvest-hut|Of the autumn rice-field;|And my sleeves are growing wet|With the moisture dripping through.",
			mark_n: 5,
			mark_x: 1,
			mark_y: 3},
		poem_2:{	
			sound1: recording_002_a, sound2: recording_002_b,
			poem:"はるすぎて　なつきにけらし　しろたへの　ころもほすてふ　あまのかぐやま",
			name_e:"持統天皇",
			part1:"はるすぎてなつきにけらししろたへの",
			part2:"ころもほすてふあまのかぐやま",
			line1:"ころもほす",
			line2:"てふあまの",
			line3:"かぐやま",
			name_j: "Jito Tenno",
			second_verse_answer: "ころもほ",
			kimariji: "はるす",
			translation: "The spring has passed|And the summer come again;|For the silk-white robes,|So they say, are spread to dry|On the \"Mount of Heaven's Perfume.\"",
			mark_n: 2,
			mark_x: 1,
			mark_y: 4},
		poem_3:{	
			sound1: recording_003_a, sound2: recording_003_b,
			poem:"あしびきの　やまどりのをの　しだりをの　ながながしよを　ひとりかもねむ",
			name_e:"柿本人麻呂",
			part1:"あしびきのやまどりのをのしだりをの",
			part2:"ながながしよをひとりかもねむ",
			line1:"ながながし",
			line2:"よをひとり",
			line3:"かもねむ",
			name_j: "Kakinomoto no Hitomaro",
			second_verse_answer: "なかな",
			kimariji: "あし",
			translation: "Oh, the foot-drawn trail|Of the mountain-pheasant's tail|Drooped like down-curved branch!|Through this long, long-dragging night|Must I lie in bed alone",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_4:{	
			sound1: recording_004_a, sound2: recording_004_b,
			poem:"たごのうらに　うちいでてみれば　しろたへの　ふじのたかねに　ゆきはふりつつ",
			name_e:"山部赤人",
			part1:"たごのうらにうちいでてみればしろたへの",
			part2:"ふじのたかねにゆきはふりつつ",
			line1:"ふじのたか",
			line2:"ねにゆきは",
			line3:"ふりつつ",
			name_j: "Yamabe no Akahito",
			second_verse_answer: "ふし",
			kimariji: "たご",
			translation: "When I take the path|To Tago's coast, I see|Perfect whiteness laid|On Mount Fuji's lofty peak|By the drift of falling snow.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_5:{	
			sound1: recording_005_a, sound2: recording_005_b,
			poem:"おくやまに　もみぢふみわけ　なくしかの　こゑきくときぞ　あきはかなしき",
			name_e:"猿丸大夫",
			part1:"おくやまにもみぢふみわけなくしかの",
			part2:"こゑきくときぞあきはかなしき",
			line1:"こゑきくと",
			line2:"きぞあきは",
			line3:"かなしき",
			name_j: "Sarumaru Dayu",
			second_verse_answer: "こゑ",
			kimariji: "おく",
			translation: "In the mountain depths,|Treading through the crimson leaves,|The wandering stag calls.|When I hear the lonely cry,|Sad--how sad!--the autumn is.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_6:{	
			sound1: recording_006_a, sound2: recording_006_b,
			poem:"かささぎの　わたせるはしに　おくしもの　しろきをみれば　よぞふけにける",
			name_e:"中納言家持",
			part1:"かささぎのわたせるはしにおくしもの",
			part2:"しろきをみればよぞふけにける",
			line1:"しろきをみ",
			line2:"ればよぞふ",
			line3:"けにける",
			name_j: "Chunagon Yakamochi",
			second_verse_answer: "しろ",
			kimariji: "かさ",
			translation: "If I see that bridge|That is spanned by flights of magpies|Across the arc of heaven|Made white with a deep-laid frost,|Then the night is almost past.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_7:{//あまの	
			sound1: recording_007_a, sound2: recording_007_b,
			poem:"あまのはら　ふりさけみれば　かすがなる　みかさのやまに　いでしつきかも",
			name_e:"安倍仲麿",
			part1:"あまのはらふりさけみればかすがなる",
			part2:"みかさのやまにいでしつきかも",
			line1:"みかさのや",
			line2:"まにいでし",
			line3:"つきかも",
			name_j: "Abe no Nakamaro",
			second_verse_answer: "みか",
			kimariji: "あまの",
			translation: "When I look up at|The wide-stretched plain of heaven,|Is the moon the same|That rose on Mount Mikasa|In the land of Kasuga",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_8:{	
			sound1: recording_008_a, sound2: recording_008_b,
			poem:"わがいほは　みやこのたつみ　しかぞすむ　よをうぢやまと　ひとはいふなり",
			name_e:"喜撰法師",
			part1:"わがいほはみやこのたつみしかぞすむ",
			part2:"よをうぢやまとひとはいふなり",
			line1:"よをうぢや",
			line2:"まとひとは",
			line3:"いふなり",
			name_j: "Kisen Hoshi ",
			second_verse_answer: "よをう",
			kimariji: "わがい",
			translation: "My lowly hut is|Southeast from the capital.|Thus I choose to live.|And the world in which I live|Men have named a \"Mount of Gloom.\"",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_9:{	
			sound1: recording_009_a, sound2: recording_009_b,
			poem:"はなのいろは　うつりにけりな　いたづらに　わがみよにふる　ながめせしまに",
			name_e:"小野小町",
			part1:"はなのいろはうつりにけりないたづらに",
			part2:"わがみよにふるながめせしまに",
			line1:"わがみよに",
			line2:"ふるながめ",
			line3:"せしまに",
			name_j: "Ono no Komachi",
			second_verse_answer: "わかみよ",
			kimariji: "はなの",
			translation: "Color of the flower|Has already faded away,|While in idle thoughts|My life passes vainly by,|As I watch the long rains fall.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_10:{	
			sound1: recording_010_a, sound2: recording_010_b,
			poem:"これやこの　ゆくもかへるも　わかれては　しるもしらぬも　あふさかのせき",
			name_e:"蝉丸",
			part1:"これやこのゆくもかへるもわかれては",
			part2:"しるもしらぬもあふさかのせき",
			line1:"しるもしら",
			line2:"ぬもあふさ",
			line3:"かのせき",
			name_j: "Semimaru",
			second_verse_answer: "しる",
			kimariji: "これ",
			translation: "Truly, this is where|Travelers who go or come|Over parting ways--|Friends or strangers--all must meet:|The gate of \"Meeting Hill.\"",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_11:{	
			sound1: recording_011_a, sound2: recording_011_b,
			poem:"わたのはら　やそしまかけて　こぎいでぬと　ひとにはつげよ　あまのつりぶね",
			name_e:"参議篁",
			part1:"わたのはらやそしまかけてこぎいでぬと",
			part2:"ひとにはつげよあまのつりぶね",
			line1:"ひとにはつ",
			line2:"げよあまの",
			line3:"つりぶね",
			name_j: "Sangi Takamura",
			second_verse_answer: "ひとには",
			kimariji: "わたのはらや",
			translation: "Over the wide sea|Towards its many distant isles|My ship sets sail.|Will the fishing boats thronged here|Proclaim my journey to the world",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_12:{//あまつ	
			sound1: recording_012_a, sound2: recording_012_b,
			poem:"あまつかぜ　くものかよひぢ　ふきとぢよ　をとめのすがた　しばしとどめむ",
			name_e:"僧正遍照",
			part1:"あまつかぜくものかよひぢふきとぢよ",
			part2:"をとめのすがたしばしとどめむ",
			line1:"をとめのす",
			line2:"がたしばし",
			line3:"とどめむ",
			name_j: "Sojo Henjo",
			second_verse_answer: "を",
			kimariji: "あまつ",
			translation: "Let the winds of heaven|Blow through the paths among the clouds|And close their gates.|Then for a while I could detain|These messengers in maiden form.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_13:{	
			sound1: recording_013_a, sound2: recording_013_b,
			poem:"つくばねの　みねよりおつる　みなのがは　こひぞつもりて　ふちとなりぬる",
			name_e:"陽成院",
			part1:"つくばねのみねよりおつるみなのがは",
			part2:"こひぞつもりてふちとなりぬる",
			line1:"こひぞつも",
			line2:"りてふちと",
			line3:"なりぬる",
			name_j: "Yozei In ",
			second_verse_answer: "こひそ",
			kimariji: "つく",
			translation: "From Tsukuba's peak|Falling waters have become|Mina's still, full flow:|So my love has grown to be|Like the river's quiet deeps.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_14:{	
			sound1: recording_014_a, sound2: recording_014_b,
			poem:"みちのくの　しのぶもぢずり　たれゆゑに　みだれそめにし　われならなくに",
			name_e:"河原左大臣",
			part1:"みちのくのしのぶもぢずりたれゆゑに",
			part2:"みだれそめにしわれならなくに",
			line1:"みだれそめ",
			line2:"にしわれな",
			line3:"らなくに",
			name_j: "Kawara no Sadaijin",
			second_verse_answer: "みたれそ",
			kimariji: "みち",
			translation: "Like Michinoku prints|Of the tangled leaves of ferns,|It is because of you|That I have become confused;|But my love for you remains.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_15:{	
			sound1: recording_015_a, sound2: recording_015_b,
			poem:"きみがため　はるののにいでて　わかなつむ　わがころもでに　ゆきはふりつつ",
			name_e:"光孝天皇",
			part1:"きみがためはるののにいでてわかなつむ",
			part2:"わがころもでにゆきはふりつつ",
			line1:"わがころも",
			line2:"でにゆきは",
			line3:"ふりつつ",
			name_j: "Koko Tenno",
			second_verse_answer: "わかころもてに",
			kimariji: "きみがためは",
			translation: "It is for your sake|That I walk the fields in spring,|Gathering green herbs,|While my garment's hanging sleeves|Are speckled with falling snow.",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_16:{	
			sound1: recording_016_a, sound2: recording_016_b,
			poem:"たちわかれ　いなばのやまの　みねにおふる　まつとしきかば　いまかへりこむ",
			name_e:"中納言行平",
			part1:"たちわかれいなばのやまのみねにおふる",
			part2:"まつとしきかばいまかへりこむ",
			line1:"まつとしき",
			line2:"かばいまか",
			line3:"へりこむ",
			name_j: "Chunagon Yukihira",
			second_verse_answer: "まつと",
			kimariji: "たち",
			translation: "Though we are parted,|If on Mount Inaba's peak|I should hear the sound|Of the pine trees growing there,|I'll come back again to you.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_17:{	
			sound1: recording_017_a, sound2: recording_017_b,
			poem:"ちはやぶる　かみよもきかず　たつたがは　からくれなゐに　みづくくるとは",
			name_e:"在原業平朝臣",
			part1:"ちはやぶるかみよもきかずたつたがは",
			part2:"からくれなゐにみづくくるとは",
			line1:"からくれな",
			line2:"ゐにみづく",
			line3:"くるとは",
			name_j: "Ariwara no Narihira Ason",
			second_verse_answer: "から",
			kimariji: "ちは",
			translation: "Even when the gods|Held sway in the ancient days,|I have never heard|That water gleamed with autumn red|As it does in Tatta's stream",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_18:{	
			sound1: recording_018_a, sound2: recording_018_b,
			poem:"すみのえの　きしによるなみ　よるさへや　ゆめのかよひぢ　ひとめよくらむ",
			name_e:"藤原敏行朝臣",
			part1:"すみのえのきしによるなみよるさへや",
			part2:"ゆめのかよひぢひとめよくらむ",
			line1:"ゆめのかよ",
			line2:"ひぢひとめ",
			line3:"よくらむ",
			name_j: "Fujiwara no Toshiyuki Ason",
			second_verse_answer: "ゆめ",
			kimariji: "す",
			translation: "The waves are gathered|On the shore of Sumi Bay,|And in the gathered night,|When in dreams I go to you,|I hide from people's eyes.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_19:{	
			sound1: recording_019_a, sound2: recording_019_b,
			poem:"なにはがた　みじかきあしの　ふしのまも　あはでこのよを　すぐしてよとや",
			name_e:"伊勢",
			part1:"なにはがたみじかきあしのふしのまも",
			part2:"あはでこのよをすぐしてよとや",
			line1:"あはでこの",
			line2:"よをすぐし",
			line3:"てよとや",
			name_j: "Ise",
			second_verse_answer: "あはて",
			kimariji: "なにわが",
			translation: "Even for a time|Short as a piece of the reeds|In Naniwa's marsh,|We must never meet again:|Is this what you are asking me",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_20:{	
			sound1: recording_020_a, sound2: recording_020_b,
			poem:"わびぬれば　いまはたおなじ　なにはなる　みをつくしても　あはむとぞおもふ",
			name_e:"元良親王",
			part1:"わびぬればいまはたおなじなにはなる",
			part2:"みをつくしてもあはむとぞおもふ",
			line1:"みをつくし",
			line2:"てもあはむ",
			line3:"とぞおもふ",
			name_j: "Motoyoshi Shinno",
			second_verse_answer: "みをつくしても",
			kimariji: "わび",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_21:{	
			sound1: recording_021_a, sound2: recording_021_b,
			poem:"いまこむと　いひしばかりに　ながつきの　ありあけのつきを　まちいでつるかな",
			name_e:"素性法師",
			part1:"いまこむといひしばかりにながつきの",
			part2:"ありあけのつきをまちいでつるかな",
			line1:"ありあけの",
			line2:"つきをまち",
			line3:"いでつるかな",
			name_j: "Sosei Hoshi",
			second_verse_answer: "あり",
			kimariji: "いまこ",
			translation: "Just because she said,|\"In a moment I will come,\"|I've awaited her|Until the moon of daybreak,|In the long month, has appeared.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_22:{	
			sound1: recording_022_a, sound2: recording_022_b,
			poem:"ふくからに　あきのくさきの　しをるれば　むべやまかぜを　あらしといふらむ",
			name_e:"文屋康秀",
			part1:"ふくからにあきのくさきのしをるれば",
			part2:"むべやまかぜをあらしといふらむ",
			line1:"むべやまか",
			line2:"ぜをあらし",
			line3:"といふらむ",
			name_j: "Fun'ya no Yasuhide",
			second_verse_answer: "むへ",
			kimariji: "ふ",
			translation: "It is by its breath|That autumn's leaves of trees and grass|Are wasted and driven.|So they call this mountain wind|The wild one, the destroyer.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_23:{	
			sound1: recording_023_a, sound2: recording_023_b,
			poem:"つきみれば　ちぢにものこそ　かなしけれ　わがみひとつの　あきにはあらねど",
			name_e:"大江千里",
			part1:"つきみればちぢにものこそかなしけれ",
			part2:"わがみひとつのあきにはあらねど",
			line1:"わがみひと",
			line2:"つのあきに",
			line3:"はあらねど",
			name_j: "Oe no Chisato",
			second_verse_answer: "わかみひ",
			kimariji: "つき",
			translation: "As I view the moon,|Many things come into my mind,|And my thoughts are sad;|Yet it's not for me alone,|That the autumn time has come.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_24:{	
			sound1: recording_024_a, sound2: recording_024_b,
			poem:"このたびは　ぬさもとりあへず　たむけやま　もみぢのにしき　かみのまにまに",
			name_e:"菅家",
			part1:"このたびはぬさもとりあへずたむけやま",
			part2:"もみぢのにしきかみのまにまに",
			line1:"もみぢのに",
			line2:"しきかみの",
			line3:"まにまに",
			name_j: "Kan Ke",
			second_verse_answer: "もみ",
			kimariji: "この",
			translation: "At the present time,|Since I could bring no offering,|See Mount Tamuke!|Here are brocades of red leaves,|As a tribute to the gods.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_25:{	
			sound1: recording_025_a, sound2: recording_025_b,
			poem:"なにしおはば　あふさかやまの　さねかづら　ひとにしられで　くるよしもがな",
			name_e:"三条右大臣",
			part1:"なにしおはばあふさかやまのさねかづら",
			part2:"ひとにしられでくるよしもがな",
			line1:"ひとにしら",
			line2:"れでくるよ",
			line3:"しもがな",
			name_j: "Sanjo Udaijin",
			second_verse_answer: "ひとにし",
			kimariji: "なにし",
			translation: "If your name is true,|Trailing vine of \"Meeting Hill,\"|Isn't there some way,|Hidden from people's gaze,|That you can draw her to my side",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_26:{	
			sound1: recording_026_a, sound2: recording_026_b,
			poem:"をぐらやま　みねのもみぢば　こころあらば　いまひとたびの　みゆきまたなむ",
			name_e:"貞信公",
			part1:"をぐらやまみねのもみぢばこころあらば",
			part2:"いまひとたびのみゆきまたなむ",
			line1:"いまひとた",
			line2:"びのみゆき",
			line3:"またなむ",
			name_j: "Teishin Ko",
			second_verse_answer: "いまひとたひのみ",
			kimariji: "おぐ",
			translation: "If the maple leaves|On Ogura mountain|Could only have hearts,|They would longingly await|The emperor's pilgrimage.",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_27:{	
			sound1: recording_027_a, sound2: recording_027_b,
			poem:"みかのはら　わきてながるる　いづみがは　いつみきとてか　こひしかるらむ",
			name_e:"中納言兼輔",
			part1:"みかのはらわきてながるるいづみがは",
			part2:"いつみきとてかこひしかるらむ",
			line1:"いつみきと",
			line2:"てかこひし",
			line3:"かるらむ",
			name_j: "Chunagon Kanesuke",
			second_verse_answer: "いつみ",
			kimariji: "みかの",
			translation: "Over Mika's plain,|Gushing forth and flowing free,|Is Izumi's stream.|I do not know if we have met:|Why, then, do I long for her",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_28:{	
			sound1: recording_028_a, sound2: recording_028_b,
			poem:"やまざとは　ふゆぞさびしさ　まさりける　ひとめもくさも　かれぬとおもへば",
			name_e:"源宗于朝臣",
			part1:"やまざとはふゆぞさびしさまさりける",
			part2:"ひとめもくさもかれぬとおもへば",
			line1:"ひとめもく",
			line2:"さもかれぬ",
			line3:"とおもへば",
			name_j: "Minamoto no Muneyuki Ason",
			second_verse_answer: "ひとめ",
			kimariji: "やまざ",
			translation: "Winter loneliness|In a mountain village grows|Only deeper, when|Guests are gone, and leaves and grass|Are withered: troubling thoughts.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_29:{	
			sound1: recording_029_a, sound2: recording_029_b,
			poem:"こころあてに　をらばやをらむ　はつしもの　おきまどはせる　しらぎくのはな",
			name_e:"凡河内躬恒",
			part1:"こころあてにをらばやをらむはつしもの",
			part2:"おきまどはせるしらぎくのはな",
			line1:"おきまどは",
			line2:"せるしらぎ",
			line3:"くのはな",
			name_j: "Oshikochi no Mitsune",
			second_verse_answer: "お",
			kimariji: "こころあ",
			translation: "If it were my wish|To pick the white chrysanthemums,|Puzzled by the frost|Of the early autumn time,|I by chance might pluck the flower.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_30:{//ありあ	
			sound1: recording_030_a, sound2: recording_030_b,
			poem:"ありあけの　つれなくみえし　わかれより　あかつきばかり　うきものはなし",
			name_e:"壬生忠岑",
			part1:"ありあけのつれなくみえしわかれより",
			part2:"あかつきばかりうきものはなし",
			line1:"あかつきば",
			line2:"かりうきも",
			line3:"のはなし",
			name_j: "Mibu no Tadamine",
			second_verse_answer: "あか",
			kimariji: "ありあ",
			translation: "Like the morning moon,|Cold, unpitying was my love.|And since we parted,|I dislike nothing so much|As the breaking light of day.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_31:{	
			sound1: recording_031_a, sound2: recording_031_b,
			poem:"あさぼらけ　ありあけのつきと　みるまでに　よしののさとに　ふれるしらゆき",
			name_e:"坂上是則",
			part1:"あさぼらけありあけのつきとみるまでに",
			part2:"よしののさとにふれるしらゆき",
			line1:"よしののさ",
			line2:"とにふれる",
			line3:"しらゆき",
			name_j: "Sakanoue no Korenori",
			second_verse_answer: "よし",
			kimariji: "あさぼらけあ",
			translation: "At the break of day,|Just as though the morning moon|Lightened the dim scene,|Yoshino's village lay|In a haze of falling snow.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_32:{	
			sound1: recording_032_a, sound2: recording_032_b,
			poem:"やまがはに　かぜのかけたる　しがらみは　ながれもあへぬ　もみぢなりけり",
			name_e:"春道列樹",
			part1:"やまがはにかぜのかけたるしがらみは",
			part2:"ながれもあへぬもみぢなりけり",
			line1:"ながれもあ",
			line2:"へぬもみぢ",
			line3:"なりけり",
			name_j: "Harumichi no Tsuraki",
			second_verse_answer: "なかれ",
			kimariji: "やまが",
			translation: "In a mountain stream|There is a wattled barrier|Built by the busy wind.|Yet it's only maple leaves,|Powerless to flow away.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_33:{	
			sound1: recording_033_a, sound2: recording_033_b,
			poem:"ひさかたの　ひかりのどけき　はるのひに　しづごころなく　はなのちるらむ",
			name_e:"紀友則",
			part1:"ひさかたのひかりのどけきはるのひに",
			part2:"しづごころなくはなのちるらむ",
			line1:"しづごころ",
			line2:"なくはなの",
			line3:"ちるらむ",
			name_j: "Ki no Tomonori",
			second_verse_answer: "しつ",
			kimariji: "ひさ",
			translation: "In the peaceful light|Of the ever-shining sun|In the days of spring,|Why do the cherry's new-blown blooms|Scatter like restless thoughts",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_34:{	
			sound1: recording_034_a, sound2: recording_034_b,
			poem:"たれをかも　しるひとにせむ　たかさごの　まつもむかしの　ともならなくに",
			name_e:"藤原興風",
			part1:"たれをかもしるひとにせむたかさごの",
			part2:"まつもむかしのともならなくに",
			line1:"まつもむか",
			line2:"しのともな",
			line3:"らなくに",
			mark_s:"たれ",
			name_j: "Fujiwara no Okikaze",
			second_verse_answer: "まつも",
			kimariji: "たれ",
			translation: "Who is still alive|When I have grown so old|That I can call my friends|Even Takasago's pines|No longer offer comfort.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_35:{	
			sound1: recording_035_a, sound2: recording_035_b,
			poem:"ひとはいさ　こころもしらず　ふるさとは　はなぞむかしの　かににほひける",
			name_e:"紀貫之",
			part1:"ひとはいさこころもしらずふるさとは",
			part2:"はなぞむかしのかににほひける",
			line1:"はなぞむか",
			line2:"しのかにに",
			line3:"ほひける",
			name_j: "Ki no Tsurayuki",
			second_verse_answer: "はなそ",
			kimariji: "ひとは",
			translation: "The depths of the hearts|Of humankind cannot be known.|But in my birthplace|The plum blossoms smell the same|As in the years gone by.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_36:{	
			sound1: recording_036_a, sound2: recording_036_b,
			poem:"なつのよは　まだよひながら　あけぬるを　くものいづこに　つきやどるらむ",
			name_e:"清原深養父",
			part1:"なつのよはまだよひながらあけぬるを",
			part2:"くものいづこにつきやどるらむ",
			line1:"くものいづ",
			line2:"こにつきや",
			line3:"どるらむ",
			name_j: "Kiyohara no Fukayabu",
			second_verse_answer: "くもの",
			kimariji: "なつ",
			translation: "In the summer night|The evening still seems present,|But the dawn is here.|To what region of the clouds|Has the wandering moon come home",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_37:{	
			sound1: recording_037_a, sound2: recording_037_b,
			poem:"しらつゆに　かぜのふきしく　あきののは　つらぬきとめぬ　たまぞちりける",
			name_e:"文屋朝康",
			part1:"しらつゆにかぜのふきしくあきののは",
			part2:"つらぬきとめぬたまぞちりける",
			line1:"つらぬきと",
			line2:"めぬたまぞ",
			line3:"ちりける",
			name_j: "Fun'ya no Asayasu",
			second_verse_answer: "つ",
			kimariji: "しら",
			translation: "In the autumn fields|When the heedless wind blows by|Over the pure-white dew,|How the myriad unstrung gems|Are scattered everywhere around",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_38:{	
			sound1: recording_038_a, sound2: recording_038_b,
			poem:"わすらるる　みをばおもはず　ちかひてし　ひとのいのちの　をしくもあるかな",
			name_e:"右近",
			part1:"わすらるるみをばおもはずちかひてし",
			part2:"ひとのいのちのをしくもあるかな",
			line1:"ひとのいの",
			line2:"ちのをしく",
			line3:"もあるかな",
			name_j: "Ukon",
			second_verse_answer: "ひとの",
			kimariji: "わすら",
			translation: "Though he forsook me,|For myself I do not care:|He made a promise,|And his life, who is forsworn,|Oh how pitiful that is.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_39:{//あさじ	
			sound1: recording_039_a, sound2: recording_039_b,
			poem:"あさぢふの　をののしのはら　しのぶれど　あまりてなどか　ひとのこひしき",
			name_e:"参議等",
			part1:"あさぢふのをののしのはらしのぶれど",
			part2:"あまりてなどかひとのこひしき",
			line1:"あまりてな",
			line2:"どかひとの",
			line3:"こひしき",
			name_j: "Sangi Hitoshi",
			second_verse_answer: "あまり",
			kimariji: "あさじ",
			translation: "Bamboo growing|Among the tangled reeds|Like my hidden love:|But it is too much to bear|That I still love her so.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_40:{	
			sound1: recording_040_a, sound2: recording_040_b,
			poem:"しのぶれど　いろにいでにけり　わがこひは　ものやおもふと　ひとのとふまで",
			name_e:"平兼盛",
			part1:"しのぶれどいろにいでにけりわがこひは",
			part2:"ものやおもふとひとのとふまで",
			line1:"ものやおも",
			line2:"ふとひとの",
			line3:"とふまで",
			name_j: "Taira no Kanemori",
			second_verse_answer: "もの",
			kimariji: "しの",
			translation: "Though I would hide it,|In my face it still appears--|My fond, secret love.|And now he questions me:|\"Is something bothering you\"",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_41:{	
			sound1: recording_041_a, sound2: recording_041_b,
			poem:"こひすてふ　わがなはまだき　たちにけり　ひとしれずこそ　おもひそめしか",
			name_e:"壬生忠見",
			part1:"こひすてふわがなはまだきたちにけり",
			part2:"ひとしれずこそおもひそめしか",
			line1:"ひとしれず",
			line2:"こそおもひ",
			line3:"そめしか",
			name_j: "Mibu no Tadami",
			second_verse_answer: "ひとし",
			kimariji: "こい",
			translation: "It is true I love,|But the rumor of my love|Had gone far and wide,|When people should not have known|That I had begun to love.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_42:{	
			sound1: recording_042_a, sound2: recording_042_b,
			poem:"ちぎりきな　かたみにそでを　しぼりつつ　すゑのまつやま　なみこさじとは",
			name_e:"清原元輔",
			part1:"ちぎりきなかたみにそでをしぼりつつ",
			part2:"すゑのまつやまなみこさじとは",
			line1:"すゑのまつ",
			line2:"やまなみこ",
			line3:"さじとは",
			name_j: "Kiyohara no Motosuke",
			second_verse_answer: "す",
			kimariji: "ちぎりき",
			translation: "Our sleeves were wet with tears|As pledges that our love--|Will last until|Over Sue's Mount of Pines|Ocean waves are breaking.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_43:{//あい	
			sound1: recording_043_a, sound2: recording_043_b,
			poem:"あひみての　のちのこころに　くらぶれば　むかしはものを　おもはざりけり",
			name_e:"権中納言敦忠",
			part1:"あひみてののちのこころにくらぶれば",
			part2:"むかしはものをおもはざりけり",
			line1:"むかしはも",
			line2:"のをおもは",
			line3:"ざりけり",
			name_j: "Gon Chunagon Atsutada",
			second_verse_answer: "むか",
			kimariji: "あい",
			translation: "I have met my love.|When I compare this present|With feelings of the past,|My passion is now as if|I have never loved before.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_44:{	
			sound1: recording_044_a, sound2: recording_044_b,
			poem:"あふことの　たえてしなくは　なかなかに　ひとをもみをも　うらみざらまし",
			name_e:"中納言朝忠",
			part1:"あふことのたえてしなくはなかなかに",
			part2:"ひとをもみをもうらみざらまし",
			line1:"ひとをもみ",
			line2:"をもうらみ",
			line3:"ざらまし",
			name_j: "Chunagon Asatada",
			second_verse_answer: "ひとを",
			kimariji: "おおこ",
			translation: "If it should happen|That we never met again,|I would not complain;|And I doubt that she or I|Would feel that we were left alone.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_45:{//あわれ	
			sound1: recording_045_a, sound2: recording_045_b,
			poem:"あはれとも　いふべき人は　思ほえで　みのいたづらに　なりぬべきかな",
			name_e:"謙徳公",
			part1:"あはれともいふべき人は思ほえで",
			part2:"みのいたづらになりぬべきかな",
			line1:"みのいたづ",
			line2:"らになりぬ",
			line3:"べきかな",
			name_j: "Kentoku Ko",
			second_verse_answer: "みの",
			kimariji: "あわれ",
			translation: "Surely there is none|Who will speak a pitying word|About my lost love.|Now my folly's fitting end|Is my own nothingness.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_46:{	
			sound1: recording_046_a, sound2: recording_046_b,
			poem:"ゆらのとを　わたるふなびと　かぢをたえ　ゆくへもしらぬ　こひのみちかな",
			name_e:"曾禰好忠",
			part1:"ゆらのとをわたるふなびとかぢをたえ",
			part2:"ゆくへもしらぬこひのみちかな",
			line1:"ゆくへもし",
			line2:"らぬこひの",
			line3:"みちかな",
			name_j: "Sone no Yoshitada",
			second_verse_answer: "ゆく",
			kimariji: "ゆら",
			translation: "Like a mariner|Sailing over Yura's strait|With his rudder gone:|Where, over the deep of love,|The end lies, I do not know.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_47:{	
			sound1: recording_047_a, sound2: recording_047_b,
			poem:"やへむぐら　しげれるやどの　さびしきに　ひとこそみえね　あきはきにけり",
			name_e:"恵慶法師",
			part1:"やへむぐらしげれるやどのさびしきに",
			part2:"ひとこそみえねあきはきにけり",
			line1:"ひとこそみ",
			line2:"えねあきは",
			line3:"きにけり",
			name_j: "Egyo Hoshi",
			second_verse_answer: "ひとこそみ",
			kimariji: "やえ",
			translation: "To the dim cottage|Overgrown with thick-leaved vines|In its loneliness|Comes the dreary autumn time:|But there no people come.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_48:{	
			sound1: recording_048_a, sound2: recording_048_b,
			poem:"かぜをいたみ　いはうつなみの　おのれのみ　くだけてものを　おもふころかな",
			name_e:"源重之",
			part1:"かぜをいたみいはうつなみのおのれのみ",
			part2:"くだけてものをおもふころかな",
			line1:"くだけても",
			line2:"のをおもふ",
			line3:"ころかな",
			name_j: "Minamoto no Shigeyuki",
			second_verse_answer: "くた",
			kimariji: "かぜを",
			translation: "Like a driven wave,|Dashed by fierce winds on a rock,|So am I:  alone|And crushed upon the shore,|Remembering what has been.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_49:{	
			sound1: recording_049_a, sound2: recording_049_b,
			poem:"みかきもり　ゑじのたくひの　よるはもえ　ひるはきえつつ　ものをこそおもへ",
			name_e:"大中臣能宣",
			part1:"みかきもりゑじのたくひのよるはもえ",
			part2:"ひるはきえつつものをこそおもへ",
			line1:"ひるはきえ",
			line2:"つつものを",
			line3:"こそおもへ",
			name_j: "Onakatomi no Yoshinobu Ason",
			second_verse_answer: "ひる",
			kimariji: "みかき",
			translation: "Like the guard's fires|Kept at the imperial gateway--|Burning through the night,|Dull in ashes through the day--|Is the love aglow in me.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_50:{	
			sound1: recording_050_a, sound2: recording_050_b,
			poem:"きみがため　をしからざりし　いのちさへ　ながくもがなと　おもひけるかな",
			name_e:"藤原義孝",
			part1:"きみがためをしからざりしいのちさへ",
			part2:"ながくもがなとおもひけるかな",
			line1:"ながくもが",
			line2:"なとおもひ",
			line3:"けるかな",
			name_j: "Fujiwara no Yoshitaka",
			second_verse_answer: "なかく",
			kimariji: "きみがためお",
			translation: "For your precious sake,|Once my eager life itself|Was not dear to me.|But now it is my heart's desire|It may long, long years endure.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_51:{	
			sound1: recording_051_a, sound2: recording_051_b,
			poem:"かくとだに　えやはいぶきの　さしもぐさ　さしもしらじな　もゆるおもひを",
			name_e:"藤原実方朝臣",
			part1:"かくとだにえやはいぶきのさしもぐさ",
			part2:"さしもしらじなもゆるおもひを",
			line1:"さしもしら",
			line2:"じなもゆる",
			line3:"おもひを",
			name_j: "Fujiwara no Sanekata Ason",
			second_verse_answer: "さ",
			kimariji: "かく",
			translation: "How can I tell her|How fierce my love for her is|Will she understand|That the love I feel for her|Burns like Ibuki's fire plant",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_52:{	
			sound1: recording_052_a, sound2: recording_052_b,
			poem:"あけぬれば　くるるものとは　しりながら　なほうらめしき　あさぼらけかな",
			name_e:"藤原道信朝臣",
			part1:"あけぬればくるるものとはしりながら",
			part2:"なほうらめしきあさぼらけかな",
			line1:"なほうらめ",
			line2:"しきあさぼ",
			line3:"らけかな",
			name_j: "Fujiwara no Michinobu Ason",
			second_verse_answer: "なほう",
			kimariji: "あけ",
			translation: "Though I know indeed|That the night will come again|After day has dawned,|Still, in truth, I hate the sight|Of the morning's coming light.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_53:{	
			sound1: recording_053_a, sound2: recording_053_b,
			poem:"なげきつつ　ひとりぬるよの　あくるまは　いかにひさしき　ものとかはしる",
			name_e:"右大将道綱母",
			part1:"なげきつつひとりぬるよのあくるまは",
			part2:"いかにひさしきものとかはしる",
			line1:"いかにひさ",
			line2:"しきものと",
			line3:"かはしる",
			name_j: "Udaisho Michitsuna no Haha",
			second_verse_answer: "いか",
			kimariji: "なげき",
			translation: "Lying all alone,|Through the hours of the night,|Till the daylight comes:|Can you realize at all|The emptiness of that night",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_54:{	
			sound1: recording_054_a, sound2: recording_054_b,
			poem:"わすれじの　ゆくすゑまでは　かたければ　けふをかぎりの　いのちともがな",
			name_e:"儀同三司母",
			part1:"わすれじのゆくすゑまではかたければ",
			part2:"けふをかぎりのいのちともがな",
			line1:"けふをかぎ",
			line2:"りのいのち",
			line3:"ともがな",
			name_j: "Gido Sanshi no Haha",
			second_verse_answer: "けふを",
			kimariji: "わすれ",
			translation: "If remembering me|Will for him in future years|Be too difficult,|It would be well this very day|That I should end my life.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_55:{	
			sound1: recording_055_a, sound2: recording_055_b,
			poem:"たきのおとは　たえてひさしく　なりぬれど　なこそながれて　なほきこえけれ",
			name_e:"大納言公任",
			part1:"たきのおとはたえてひさしくなりぬれど",
			part2:"なこそながれてなほきこえけれ",
			line1:"なこそなが",
			line2:"れてなほき",
			line3:"こえけれ",
			name_j: "Dainagon Kinto",
			second_verse_answer: "なこ",
			kimariji: "たき",
			translation: "Though the waterfall|Ceased its flowing long ago,|And its sound is stilled,|Yet, in name it ever flows,|And in fame may yet be heard.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_56:{//あらざ	
			sound1: recording_056_a, sound2: recording_056_b,
			poem:"あらざらむ　このよのほかの　おもひでに　いまひとたびの　あふこともがな",
			name_e:"和泉式部",
			part1:"あらざらむこのよのほかのおもひでに",
			part2:"いまひとたびのあふこともがな",
			line1:"いまひとた",
			line2:"びのあふこ",
			line3:"ともがな",
			name_j: "Izumi Shikibu",
			second_verse_answer: "いまひとたひのあ",
			kimariji: "あらざ",
			translation: "Soon my life will close.|When I am beyond this world|And have forgotten it,|Let me remember only this:|One final meeting with you.",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_57:{	
			sound1: recording_057_a, sound2: recording_057_b,
			poem:"めぐりあひて　みしやそれとも　わかぬまに　くもがくれにし　よはのつきかな",
			name_e:"紫式部",
			part1:"めぐりあひてみしやそれともわかぬまに",
			part2:"くもがくれにしよはのつきかな",
			line1:"くもがくれ",
			line2:"にしよはの",
			line3:"つきかな",
			name_j: "Murasaki Shikibu",
			second_verse_answer: "くもか",
			kimariji: "め",
			translation: "Meeting on the path:|But I cannot clearly know|If it was he,|Because the midnight moon|In a cloud had disappeared.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_58:{//ありま	
			sound1: recording_058_a, sound2: recording_058_b,
			poem:"ありまやま　ゐなのささはら　かぜふけば　いでそよひとを　わすれやはする",
			name_e:"大弐三位",
			part1:"ありまやまゐなのささはらかぜふけば",
			part2:"いでそよひとをわすれやはする",
			line1:"いでそよひ",
			line2:"とをわすれ",
			line3:"やはする",
			name_j: "Daini no Sanmi",
			second_verse_answer: "いて",
			kimariji: "ありま",
			translation: "As Mount Arima|Sends its rustling winds across|Ina's bamboo plains,|I will be just as steadfast|And never will forget you.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_59:{	
			sound1: recording_059_a, sound2: recording_059_b,
			poem:"やすらはで　ねなましものを　さよふけて　かたぶくまでの　つきをみしかな",
			name_e:"赤染衛門",
			part1:"やすらはでねなましものをさよふけて",
			part2:"かたぶくまでのつきをみしかな",
			line1:"かたぶくま",
			line2:"でのつきを",
			line3:"みしかな",
			name_j: "Akazome Emon",
			second_verse_answer: "かた",
			kimariji: "やす",
			translation: "Better to have slept|Care-free, than to keep vain watch|Through the passing night,|Till I saw the lonely moon|Traverse her descending path.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_60:{//おおえ	
			sound1: recording_060_a, sound2: recording_060_b,
			poem:"おほえやま　いくののみちの　とほければ　まだふみもみず　あまのはしだて",
			name_e:"小式部内侍",
			part1:"おほえやまいくののみちのとほければ",
			part2:"まだふみもみずあまのはしだて",
			line1:"まだふみも",
			line2:"みずあまの",
			line3:"はしだて",
			name_j: "Koshikibu no Naishi",
			second_verse_answer: "また",
			kimariji: "おおえ",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_61:{	
			sound1: recording_061_a, sound2: recording_061_b,
			poem:"いにしへの　ならのみやこの　やへざくら　けふここのへに　にほひぬるかな",
			name_e:"伊勢大輔",
			part1:"いにしへのならのみやこのやへざくら",
			part2:"けふここのへににほひぬるかな",
			line1:"けふここの",
			line2:"へににほひ",
			line3:"ぬるかな",
			name_j: "Ise no Osuke",
			second_verse_answer: "けふこ",
			kimariji: "いに",
			translation: "Eight-fold cherry flowers|That at Nara--ancient seat|Of our state--have bloomed,|In our nine-fold palace court|Shed their sweet perfume today.",
			mark_n: 4,
			mark_x: 2,
			mark_y: 2},
		poem_62:{	
			sound1: recording_062_a, sound2: recording_062_b,
			poem:"よをこめて　とりのそらねは　はかるとも　よにあふさかの　せきはゆるさじ",
			name_e:"清少納言",
			part1:"よをこめてとりのそらねははかるとも",
			part2:"よにあふさかのせきはゆるさじ",
			line1:"よにあふさ",
			line2:"かのせきは",
			line3:"ゆるさじ",
			name_j: "Sei Shonagon",
			second_verse_answer: "よに",
			kimariji: "よを",
			translation: "The rooster's crowing|In the middle of the night|Deceived the hearers;|But at Osaka's gateway|The guards are never fooled.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_63:{	
			sound1: recording_063_a, sound2: recording_063_b,
			poem:"いまはただ　おもひたえなむ　とばかりを　ひとづてならで　いふよしもがな",
			name_e:"左京大夫道雅",
			part1:"いまはただおもひたえなむとばかりを",
			part2:"ひとづてならでいふよしもがな",
			line1:"ひとづてな",
			line2:"らでいふよ",
			line3:"しもがな",
			name_j: "Sakyo no Daibu Michimasa",
			second_verse_answer: "ひとつ",
			kimariji: "いまは",
			translation: "Is there any way|Except by a messenger|To send these words to you|If I could, I'd come to you|To say goodbye forever.",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_64:{//あさぼらけう	
			sound1: recording_064_a, sound2: recording_064_b,
			poem:"あさぼらけ　うぢのかはぎり　たえだえに　あらはれわたる　せぜのあじろぎ",
			name_e:"権中納言定頼",
			part1:"あさぼらけうぢのかはぎりたえだえに",
			part2:"あらはれわたるせぜのあじろぎ",
			line1:"あらはれわ",
			line2:"たるせぜの",
			line3:"あじろぎ",
			name_j: "GonChunagon Sadayori",
			second_verse_answer: "あら",
			kimariji: "あさぼらけう",
			translation: "In the early dawn|When the mists on Uji River|Slowly lift and clear,|From the shallows to the deep,|The stakes of fishing nets appear.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_65:{	
			sound1: recording_065_a, sound2: recording_065_b,
			poem:"うらみわび　ほさぬそでだに　あるものを　こひにくちなむ　なこそをしけれ",
			name_e:"相模",
			part1:"うらみわびほさぬそでだにあるものを",
			part2:"こひにくちなむなこそをしけれ",
			line1:"こひにくち",
			line2:"なむなこそ",
			line3:"をしけれ",
			name_j: "Sagami",
			second_verse_answer: "こひに",
			kimariji: "うら",
			translation: "Even when your hate|Makes me stain my sleeves with tears|In cold misery,|Worse than hate and misery|Is the loss of my good name.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_66:{	
			sound1: recording_066_a, sound2: recording_066_b,
			poem:"もろともに　あはれとおもへ　やまざくら　はなよりほかに　しるひともなし",
			name_e:"前大僧正行尊",
			part1:"もろともにあはれとおもへやまざくら",
			part2:"はなよりほかにしるひともなし",
			line1:"はなよりほ",
			line2:"かにしるひ",
			line3:"ともなし",
			name_j: "Daisojo Gyoson",
			second_verse_answer: "はなよ",
			kimariji: "もろ",
			translation: "On a mountain slope,|Solitary, uncompanioned,|Stands a cherry tree.|Except for you, lonely friend,|To others I am unknown.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_67:{	
			sound1: recording_067_a, sound2: recording_067_b,
			poem:"はるのよの　ゆめばかりなる　たまくらに　かひなくたたむ　なこそをしけれ",
			name_e:"周防内侍",
			part1:"はるのよのゆめばかりなるたまくらに",
			part2:"かひなくたたむなこそをしけれ",
			line1:"かひなくた",
			line2:"たむなこそ",
			line3:"をしけれ",
			name_j: "Suo no Naishi",
			second_verse_answer: "かひ",
			kimariji: "はるの",
			translation: "If I lay my head|Upon his arm in the dark|Of a short spring night,|This innocent dream pillow|Will be the death of my good name.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_68:{	
			sound1: recording_068_a, sound2: recording_068_b,
			poem:"こころにも　あらでうきよに　ながらへば　こひしかるべき　よはのつきかな",
			name_e:"三条院",
			part1:"こころにもあらでうきよにながらへば",
			part2:"こひしかるべきよはのつきかな",
			line1:"こひしかる",
			line2:"べきよはの",
			line3:"つきかな",
			name_j: "Sanjo In",
			second_verse_answer: "こひし",
			kimariji: "こころに",
			translation: "Though I do not want|To live on in this floating world,|If I remain here,|Let me remember only|This midnight and this moonrise.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_69:{//あらし	
			sound1: recording_069_a, sound2: recording_069_b,
			poem:"あらしふく　みむろのやまの　もみぢばは　たつたのかはの　にしきなりけり",
			name_e:"能因法師",
			part1:"あらしふくみむろのやまのもみぢばは",
			part2:"たつたのかはのにしきなりけり",
			line1:"たつたのか",
			line2:"はのにしき",
			line3:"なりけり",
			name_j: "Noin Hoshi",
			second_verse_answer: "たつ",
			kimariji: "あらし",
			translation: "By the wind storm's blast|From Mimuro's mountain slopes|Maples leaves are torn,|Which turn Tatsuta River|Into a rich brocade.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_70:{	
			sound1: recording_070_a, sound2: recording_070_b,
			poem:"さびしさに　やどをたちいでて　ながむれば　いづこもおなじ　あきのゆふぐれ",
			name_e:"良暹法師",
			part1:"さびしさにやどをたちいでてながむれば",
			part2:"いづこもおなじあきのゆふぐれ",
			line1:"いづこもお",
			line2:"なじあきの",
			line3:"ゆふぐれ",
			name_j: "Ryosen Hoshi",
			second_verse_answer: "いつこ",
			kimariji: "さ",
			translation: "In my loneliness|I leave my little hut.|When I look around,|Everywhere it is the same:|One lone, darkening autumn eve.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_71:{//あし	
			sound1: recording_071_a, sound2: recording_071_b,
			poem:"ゆふされば　かどたのいなば　おとづれて　あしのまろやに　あきかぜぞふく",
			name_e:"大納言経信",
			part1:"ゆふさればかどたのいなばおとづれて",
			part2:"あしのまろやにあきかぜぞふく",
			line1:"あしのまろ",
			line2:"やにあきか",
			line3:"ぜぞふく",
			name_j: "Dainagon Tsunenobu",
			second_verse_answer: "あし",
			kimariji: "ゆう",
			translation: "When the evening comes,|From the rice leaves at my gate,|Gentle knocks are heard,|And, into my round rush-hut,|Enters autumn's roaming breeze.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_72:{	
			sound1: recording_072_a, sound2: recording_072_b,
			poem:"おとにきく　たかしのはまの　あだなみは　かけじやそでの　ぬれもこそすれ",
			name_e:"祐子内親王家紀伊",
			part1:"おとにきくたかしのはまのあだなみは",
			part2:"かけじやそでのぬれもこそすれ",
			line1:"かけじやそ",
			line2:"でのぬれも",
			line3:"こそすれ",
			name_j: "Yushi Naishinno-ke no Kii",
			second_verse_answer: "かけ",
			kimariji: "おと",
			translation: "Famous are the waves|That break on Takashi beach|In noisy arrogance.|If I should go near that shore.|I would only wet my sleeves.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_73:{	
			sound1: recording_073_a, sound2: recording_073_b,
			poem:"たかさごの　をのへのさくら　さきにけり　とやまのかすみ　たたずもあらなむ",
			name_e:"権中納言匡房",
			part1:"たかさごのをのへのさくらさきにけり",
			part2:"とやまのかすみたたずもあらなむ",
			line1:"とやまのか",
			line2:"すみたたず",
			line3:"もあらなむ",
			name_j: "GonChunagon Masafusa",
			second_verse_answer: "と",
			kimariji: "たか",
			translation: "On that far mountain|On the slope below the peak|Cherries are in flower.|Oh, let the mountain mists|Not arise to hide the scene.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_74:{	
			sound1: recording_074_a, sound2: recording_074_b,
			poem:"うかりける　ひとをはつせの　やまおろしよ　はげしかれとは　いのらぬものを",
			name_e:"源俊頼朝臣",
			part1:"うかりけるひとをはつせのやまおろしよ",
			part2:"はげしかれとはいのらぬものを",
			line1:"はげしかれ",
			line2:"とはいのら",
			line3:"ぬものを",
			name_j: "Minamoto no Toshiyori Ason",
			second_verse_answer: "はけ",
			kimariji: "うか",
			translation: "It was not for this|I prayed at the holy shrine:|That she would become|As pitiless and as cold|As the storms on Hase's hills.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_75:{	
			sound1: recording_075_a, sound2: recording_075_b,
			poem:"ちぎりおきし　させもがつゆを　いのちにて　あはれことしの　あきもいぬめり",
			name_e:"藤原基俊",
			part1:"ちぎりおきしさせもがつゆをいのちにて",
			part2:"あはれことしのあきもいぬめり",
			line1:"あはれこと",
			line2:"しのあきも",
			line3:"いぬめり",
			name_j: "Fujiwara no Mototoshi",
			second_verse_answer: "あはれ",
			kimariji: "ちぎりお",
			translation: "As dew promises|New life to the thirsty plant,|So did your vow to me.|Yet the year has passed away,|And autumn has come again.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_76:{	
			sound1: recording_076_a, sound2: recording_076_b,
			poem:"わたのはら　こぎいでてみれば　ひさかたの　くもゐにまがふ　おきつしらなみ",
			name_e:"法性寺入道前関白太政大臣",
			part1:"わたのはらこぎいでてみればひさかたの",
			part2:"くもゐにまがふおきつしらなみ",
			line1:"くもゐにま",
			line2:"がふおきつ",
			line3:"しらなみ",
			name_j: "Hoshoji no Nyudo Kanpaku Dajodaijin",
			second_verse_answer: "くもゐ",
			kimariji: "わたのはらこ",
			translation: "Over the wide sea|As I sail and look around,|It appears to me|That the white waves, far away,|Are the ever shining sky.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_77:{	
			sound1: recording_077_a, sound2: recording_077_b,
			poem:"せをはやみ　いはにせかるる　たきがはの　われてもすゑに　あはむとぞおもふ",
			name_e:"崇徳院",
			part1:"せをはやみいはにせかるるたきがはの",
			part2:"われてもすゑにあはむとぞおもふ",
			line1:"われてもす",
			line2:"ゑにあはむ",
			line3:"とぞおもふ",
			name_j: "Sutoku In",
			second_verse_answer: "われ",
			kimariji: "せ",
			translation: "Though a swift stream is|Divided by a boulder|In its headlong flow,|Though divided, on it rushes,|And at last unites again.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_78:{//あわじ	
			sound1: recording_078_a, sound2: recording_078_b,
			poem:"あはぢしま　かよふちどりの　なくこゑに　いくよねざめぬ　すまのせきもり",
			name_e:"源兼昌",
			part1:"あはぢしまかよふちどりのなくこゑに",
			part2:"いくよねざめぬすまのせきもり",
			line1:"いくよねざ",
			line2:"めぬすまの",
			line3:"せきもり",
			name_j: "Minamoto no Kanemasa",
			second_verse_answer: "いく",
			kimariji: "あわじ",
			translation: "Guard of Suma Gate,|From your sleep, how many nights|Have you awakened|At the cries of sanderlings,|Flying from Awaji Island",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_79:{//あきか	
			sound1: recording_079_a, sound2: recording_079_b,
			poem:"あきかぜに　たなびくくもの　たえまより　もれいづるつきの　かげのさやけさ",
			name_e:"左京大夫顕輔",
			part1:"あきかぜにたなびくくものたえまより",
			part2:"もれいづるつきのかげのさやけさ",
			line1:"もれいづる",
			line2:"つきのかげ",
			line3:"のさやけさ",
			name_j: "Sakyo no Daibu Akisuke",
			second_verse_answer: "もれ",
			kimariji: "あきか",
			translation: "See how clear and bright|Is the moonlight finding ways|Through the riven clouds|That, with drifting autumn wind,|Gracefully float in the sky.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_80:{	
			sound1: recording_080_a, sound2: recording_080_b,
			poem:"ながからむ　こころもしらず　くろかみの　みだれてけさは　ものをこそおもへ",
			name_e:"待賢門院堀河",
			part1:"ながからむこころもしらずくろかみの",
			part2:"みだれてけさはものをこそおもへ",
			line1:"みだれてけ",
			line2:"さはものを",
			line3:"こそおもへ",
			name_j: "Taiken Moin no Horikawa",
			second_verse_answer: "みたれて",
			kimariji: "ながか",
			translation: "Is it forever|That he hopes our love will last|He did not answer.|And now my daylight thoughts|Are as tangled as my black hair.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_81:{	
			sound1: recording_081_a, sound2: recording_081_b,
			poem:"ほととぎす　なきつるかたを　ながむれば　ただありあけの　つきぞのこれる",
			name_e:"後徳大寺左大臣",
			part1:"ほととぎすなきつるかたをながむれば",
			part2:"ただありあけのつきぞのこれる",
			line1:"ただありあ",
			line2:"けのつきぞ",
			line3:"のこれる",
			name_j: "Go Tokudaiji no Sadaijin",
			second_verse_answer: "たた",
			kimariji: "ほ",
			translation: "When I turned my look|Toward the place where I had heard|The cuckoo's call,|The only thing I found|Was the moon of early dawn.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_82:{	
			sound1: recording_082_a, sound2: recording_082_b,
			poem:"おもひわび　さてもいのちは　あるものを　うきにたへぬは　なみだなりけり",
			name_e:"道因法師",
			part1:"おもひわびさてもいのちはあるものを",
			part2:"うきにたへぬはなみだなりけり",
			line1:"うきにたへ",
			line2:"ぬはなみだ",
			line3:"なりけり",
			name_j: "Doin Hoshi",
			second_verse_answer: "うき",
			kimariji: "おも",
			translation: "Though in deep distress|Through your cruel blow, my life|Still is left to me.|But I cannot keep my tears;|They break forth from my grief.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_83:{	
			sound1: recording_083_a, sound2: recording_083_b,
			poem:"よのなかよ　みちこそなけれ　おもひいる　やまのおくにも　しかぞなくなる",
			name_e:"皇太后宮大夫俊成",
			part1:"よのなかよみちこそなけれおもひいる",
			part2:"やまのおくにもしかぞなくなる",
			line1:"やまのおく",
			line2:"にもしかぞ",
			line3:"なくなる",
			name_j: "Kotaigogu no Daibu Toshinari",
			second_verse_answer: "やま",
			kimariji: "よのなかよ",
			translation: "From this world I think|That there is nowhere to escape.|I wanted to hide|In the mountains' farthest depths;|But there I hear the stag's cry.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_84:{//ながら	
			sound1: recording_084_a, sound2: recording_084_b,
			poem:"ながらへば　またこのごろや　しのばれむ　うしとみしよぞ　いまはこひしき",
			name_e:"藤原清輔朝臣",
			part1:"ながらへばまたこのごろやしのばれむ",
			part2:"うしとみしよぞいまはこひしき",
			line1:"うしとみし",
			line2:"よぞいまは",
			line3:"こひしき",
			name_j: "Fujiwara no Kiyosuke Ason",
			second_verse_answer: "うし",
			kimariji: "ながら",
			translation: "If I should live long,|Then perhaps the present days|May be dear to me,|Just as past time filled with grief|Comes quietly back in thought.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_85:{	
			sound1: recording_085_a, sound2: recording_085_b,
			poem:"よもすがら　ものおもふころは　あけやらで　ねやのひまさへ　つれなかりけり",
			name_e:"俊恵法師",
			part1:"よもすがらものおもふころはあけやらで",
			part2:"ねやのひまさへつれなかりけり",
			line1:"ねやのひま",
			line2:"さへつれな",
			line3:"かりけり",
			name_j: "Shun'e Hoshi",
			second_verse_answer: "ね",
			kimariji: "よも",
			translation: "Through an unsleeping night|Longingly I pass the hours,|While the day's dawn lags.|And now the bedroom shutters|Are keeping light and life from me.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_86:{	
			sound1: recording_086_a, sound2: recording_086_b,
			poem:"なげけとて　つきやはものを　おもはする　かこちがほなる　わがなみだかな",
			name_e:"西行法師",
			part1:"なげけとてつきやはものをおもはする",
			part2:"かこちがほなるわがなみだかな",
			line1:"かこちがほ",
			line2:"なるわがな",
			line3:"みだかな",
			name_j: "Saigyo Hoshi",
			second_verse_answer: "かこ",
			kimariji: "なげけ",
			translation: "Should I blame the moon|For bringing forth this sadness,|As if it pictured grief|Lifting up my troubled face,|I regard it through my tears.",
			mark_n: 3,
			mark_x: 3,
			mark_y: 1},
		poem_87:{	
			sound1: recording_087_a, sound2: recording_087_b,
			poem:"むらさめの　つゆもまだひぬ　まきのはに　きりたちのぼる　あきのゆふぐれ",
			name_e:"寂蓮法師",
			part1:"むらさめのつゆもまだひぬまきのはに",
			part2:"きりたちのぼるあきのゆふぐれ",
			line1:"きりたちの",
			line2:"ぼるあきの",
			line3:"ゆふぐれ",
			name_j: "Jakuren Hoshi",
			second_verse_answer: "き",
			kimariji: "む",
			translation: "An autumn eve:|See the valley mists arise|Among the fir leaves|That still hold the dripping wet|Of the chill day's sudden showers.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_88:{//なにわえ	
			sound1: recording_088_a, sound2: recording_088_b,
			poem:"なにはえの　あしのかりねの　ひとよゆゑ　みをつくしてや　こひわたるべき",
			name_e:"皇嘉門院別当",
			part1:"なにはえのあしのかりねのひとよゆゑ",
			part2:"みをつくしてやこひわたるべき",
			line1:"みをつくし",
			line2:"てやこひわ",
			line3:"たるべき",
			name_j: "Koka Moin no Betto",
			second_verse_answer: "みをつくしてや",
			kimariji: "なにわえ",
			translation: "After one brief night--|Short as a piece of the reeds|Growing in Naniwa bay--|Must I forever long for him|With my whole heart, till life ends",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_89:{	
			sound1: recording_089_a, sound2: recording_089_b,
			poem:"たまのをよ　たえなばたえね　ながらへば　しのぶることの　よわりもぞする",
			name_e:"式子内親王",
			part1:"たまのをよたえなばたえねながらへば",
			part2:"しのぶることのよわりもぞする",
			line1:"しのぶるこ",
			line2:"とのよわり",
			line3:"もぞする",
			name_j: "Shokushi Naishinno",
			second_verse_answer: "しの",
			kimariji: "たま",
			translation: "Like a string of gems|Grown weak, my life will break now;|For if I live on,|All I do to hide my love|May at last grow weak and fail.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_90:{	
			sound1: recording_090_a, sound2: recording_090_b,
			poem:"みせばやな　をじまのあまの　そでだにも　ぬれにぞぬれし　いろはかはらず",
			name_e:"殷富門院大輔",
			part1:"みせばやなをじまのあまのそでだにも",
			part2:"ぬれにぞぬれしいろはかはらず",
			line1:"ぬれにぞぬ",
			line2:"れしいろは",
			line3:"かはらず",
			name_j: "Inpu Moin no Taifu",
			second_verse_answer: "ぬ",
			kimariji: "みせ",
			translation: "Let me show him these!|Even the fishermen's sleeves|On Ojima's shores,|Though wet through and wet again,|Do not so change their colors.",
			mark_n: 0,
			mark_x: 3,
			mark_y: 1},
		poem_91:{	
			sound1: recording_091_a, sound2: recording_091_b,
			poem:"きりぎりす　なくやしもよの　さむしろに　ころもかたしき　ひとりかもねむ",
			name_e:"後京極摂政前太政大臣",
			part1:"きりぎりすなくやしもよのさむしろに",
			part2:"ころもかたしきひとりかもねむ",
			line1:"ころもかた",
			line2:"しきひとり",
			line3:"かもねむ",
			name_j: "Go Kyogoku no Sessho Dajodaijin",
			second_verse_answer: "ころもか",
			kimariji: "きり",
			translation: "In my cold bed,|Drawing close my folded quilt,|I sleep alone,|While all through the frosty night|I hear a cricket's lonely sound.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_92:{	
			sound1: recording_092_a, sound2: recording_092_b,
			poem:"わがそでは　しほひにみえぬ　おきのいしの　ひとこそしらね　かわくまもなし",
			name_e:"二条院讃岐",
			part1:"わがそではしほひにみえぬおきのいしの",
			part2:"ひとこそしらねかわくまもなし",
			line1:"ひとこそし",
			line2:"らねかわく",
			line3:"まもなし",
			name_j: "Nijo In no Sanuki",
			second_verse_answer: "ひとこそし",
			kimariji: "わがそ",
			translation: "Like a rock at sea,|At ebb-tide hidden from view,|Is my tear-drenched sleeve:|Never for a moment dry,|And no one knows it is there.",
			mark_n: 2,
			mark_x: 1,
			mark_y: 1},
		poem_93:{	
			sound1: recording_093_a, sound2: recording_093_b,
			poem:"よのなかは　つねにもがもな　なぎさこぐ　あまのをぶねの　つなでかなしも",
			name_e:"鎌倉右大臣",
			part1:"よのなかはつねにもがもななぎさこぐ",
			part2:"あまのをぶねのつなでかなしも",
			line1:"あまのをぶ",
			line2:"ねのつなで",
			line3:"かなしも",
			name_j: "Kamakura no Udaijin",
			second_verse_answer: "あまの",
			kimariji: "よのなかは",
			translation: "If only our world|Could be always as it is!|How moving the sight|Of the little fishing boat|Drawn by ropes along the bank.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_94:{	
			sound1: recording_094_a, sound2: recording_094_b,
			poem:"みよしのの　やまのあきかぜ　さよふけて　ふるさとさむく　ころもうつなり",
			name_e:"参議雅経",
			part1:"みよしののやまのあきかぜさよふけて",
			part2:"ふるさとさむくころもうつなり",
			line1:"ふるさとさ",
			line2:"むくころも",
			line3:"うつなり",
			name_j: "Sangi Masatsune",
			second_verse_answer: "ふる",
			kimariji: "みよ",
			translation: "From Mount Yoshino|Blows a chill, autumnal wind.|In the deepening night|The ancient village shivers:|Sounds of beating cloth I hear.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_95:{	
			sound1: recording_095_a, sound2: recording_095_b,
			poem:"おほけなく　うきよのたみに　おほふかな　わがたつそまに　すみぞめのそで",
			name_e:"前大僧正慈円",
			part1:"おほけなくうきよのたみにおほふかな",
			part2:"わがたつそまにすみぞめのそで",
			line1:"わがたつそ",
			line2:"まにすみぞ",
			line3:"めのそで",
			name_j: "Saki no Daisojo Jien",
			second_verse_answer: "わかた",
			kimariji: "おおけ",
			translation: "From the monastery|On Mount Hiei I look out|On this world of tears,|And though I am unworthy,|I shield it with my black sleeves.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_96:{	
			sound1: recording_096_a, sound2: recording_096_b,
			poem:"はなさそふ　あらしのにはの　ゆきならで　ふりゆくものは　わがみなりけり",
			name_e:"入道前太政大臣",
			part1:"はなさそふあらしのにはのゆきならで",
			part2:"ふりゆくものはわがみなりけり",
			line1:"ふりゆくも",
			line2:"のはわがみ",
			line3:"なりけり",
			name_j: "Nyudo Saki no Dajodaijin",
			second_verse_answer: "ふり",
			kimariji: "はなさ",
			translation: "Not the snow of flowers,|That the hurrying wild wind whirls|Round the garden court:|What withers and falls away|In this place is I myself.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_97:{	
			sound1: recording_097_a, sound2: recording_097_b,
			poem:"こぬひとを　まつほのうらの　ゆふなぎに　やくやもしほの　みもこがれつつ",
			name_e:"権中納言定家",
			part1:"こぬひとをまつほのうらのゆふなぎに",
			part2:"やくやもしほのみもこがれつつ",
			line1:"やくやもし",
			line2:"ほのみもこ",
			line3:"がれつつ",
			name_j: "GonChunagon Sadaie",
			second_verse_answer: "やく",
			kimariji: "こぬ",
			translation: "Like the salt sea-weed,|Burning in the evening calm.|On Matsuo's shore,|All my being is aflame,|Awaiting her who does not come.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_98:{	
			sound1: recording_098_a, sound2: recording_098_b,
			poem:"かぜそよぐ　ならのをがはの　ゆふぐれは　みそぎぞなつの　しるしなりける",
			name_e:"従二位家隆",
			part1:"かぜそよぐならのをがはのゆふぐれは",
			part2:"みそぎぞなつのしるしなりける",
			line1:"みそぎぞな",
			line2:"つのしるし",
			line3:"なりける",
			name_j: "Junii Ietaka",
			second_verse_answer: "みそ",
			kimariji: "かぜそ",
			translation: "To Nara's brook comes|Evening, and the rustling winds|Stir the oak-trees' leaves.|Not a sign of summer left|But the sacred bathing there.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_99:{	
			sound1: recording_099_a, sound2: recording_099_b,
			poem:"ひともをし　ひともうらめし　あぢきなく　よをおもふゆゑに　ものおもふみは",
			name_e:"後鳥羽院",
			part1:"ひともをしひともうらめしあぢきなく",
			part2:"よをおもふゆゑにものおもふみは",
			line1:"よをおもふ",
			line2:"ゆゑにもの",
			line3:"おもふみは",
			name_j: "Gotoba In",
			second_verse_answer: "よをお",
			kimariji: "ひとも",
			translation: "For some men I grieve;|Some men are hateful to me;|And this wretched world|To me, with all my sadness,|Is a place of misery.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},
		poem_100:{	
			sound1: recording_100_a, sound2: recording_100_b,
			poem:"ももしきや　ふるきのきばの　しのぶにも　なほあまりある　むかしなりけり",
			name_e:"順徳院",
			part1:"ももしきやふるきのきばのしのぶにも",
			part2:"なほあまりあるむかしなりけり",
			line1:"なほあまり",
			line2:"あるむかし",
			line3:"なりけり",
			name_j: "Juntoku In",
			second_verse_answer: "なほあ",
			kimariji: "もも",
			translation: "In this ancient house,|Paved with a hundred stones,|Ferns grow in the eaves;|But numerous as they are,|My old memories are more.",
			mark_n: 1,
			mark_x: 2,
			mark_y: 1},

	}
}



